// All data in one place. Bilingual HE/EN.
// Hebrew text: written for general audience, no jargon without explanation.

export const C = {
  ink: '#0a0e1a',
  navy: '#162040',
  gold: '#c8a44e',
  gL: '#e8d5a0',
  danger: '#ef4444',
  blue: '#06b6d4',
  green: '#22c55e',
  amber: '#f59e0b',
  purple: '#a855f7',
  white: '#ffffff',
};

// =================== TIMELINE (1971-2016) ===================
export const TIMELINE = [
  { date: '1971', he: 'תחילת בניית התחנה', en: 'Construction begins', cat: 'build',
    desc_he: 'התקבלה החלטה להקים את תחנת הכוח הגרעינית "ולדימיר איליץ׳ לנין" סמוך לנהר פריפיאט באוקראינה הסובייטית, 130 ק״מ צפונית לקייב.',
    desc_en: 'Decision to build the V.I. Lenin Nuclear Power Plant near the Pripyat River in Soviet Ukraine, 130 km north of Kyiv.' },
  { date: '1977', he: 'הכור הראשון מתחיל לעבוד', en: 'Unit 1 begins operation', cat: 'build',
    desc_he: 'הכור הראשון בתחנה החל לייצר חשמל. מדובר בכור מסוג RBMK-1000 בעל הספק של 1,000 מגה-וואט. התחנה נחשבה לאחת המתקדמות בברית המועצות.',
    desc_en: 'First reactor begins generating electricity. RBMK-1000 — nominal output 1,000 MWe. Considered one of the most advanced in the Soviet Union.' },
  { date: 'דצמבר 1983', he: 'הכור הרביעי — אותו זה שיתפוצץ', en: 'Unit 4 begins operation', cat: 'build',
    desc_he: 'יחידה 4 — אותו הכור שיתפוצץ ב-1986 — מתחילה לייצר חשמל. הבנייה הואצה כדי לעמוד ביעדי תכנית החומש הסובייטית. בדיקות בטיחות מסוימות נדחו לטובת לוח הזמנים.',
    desc_en: 'Unit 4 — the reactor that will explode in 1986 — begins operation. Construction was rushed to meet 5-year plan deadlines. Some safety tests were postponed.' },
  { date: '1983', he: '⚠ פגם הכור התגלה — בכור אחר', en: '⚠ Reactor flaw discovered elsewhere', cat: 'warn',
    desc_he: 'בכור זהה בליטא (איגנלינה) התגלתה תופעה מסוכנת: כפתור עצירת החירום (AZ-5) — שאמור לעצור את הכור מיד — גורם דווקא לקפיצה זמנית בעוצמה במקום לעצירה. הדיווח על התופעה הזו לא הופץ למפעילים בצ׳רנוביל. שלוש שנים לפני האסון.',
    desc_en: 'At an identical reactor in Lithuania (Ignalina), a dangerous phenomenon was discovered: the emergency stop button (AZ-5) — which should stop the reactor immediately — actually causes a temporary power surge instead. The report was NOT distributed to Chernobyl operators. Three years before the disaster.' },
  { date: '1982-1985', he: '⚠ שלושה ניסויי בטיחות נכשלו', en: '⚠ Three safety tests failed', cat: 'warn',
    desc_he: 'בתחנה תוכנן ניסוי בטיחות חשוב: לבדוק האם בעת תקלה ניתן להשתמש באנרגיית הסיבוב של הטורבינה כדי להפעיל את משאבות הקירור במשך הדקה הקריטית עד שגנרטורי הדיזל יתחילו לעבוד. שלושה ניסויים קודמים נכשלו. הניסוי הרביעי נקבע ל-25 באפריל 1986.',
    desc_en: 'A critical safety test was planned: verify whether turbine inertia can power cooling pumps during the critical minute until backup diesel generators come online. Three previous tests failed. The fourth was scheduled for 25 April 1986.' },
  { date: '25/4/1986 01:06', he: 'הכנות לניסוי הבטיחות', en: 'Test preparation', cat: 'pre',
    desc_he: 'מתחילה ההכנה לניסוי הבטיחות הרביעי בסדרה. עוצמת הכור מתחילה לרדת בהדרגה. תחנת צ׳רנוביל הפיקה אז 4,000 מגה-וואט מ-4 כורים פעילים — להשוואה, התחנה הגדולה בישראל (אורות רבין בחדרה) מפיקה 2,600 מגה-וואט.',
    desc_en: 'Preparation begins for the fourth test in the series. Reactor power starts gradually dropping. Chernobyl produced 4,000 MW from 4 active reactors — for comparison, Israel\'s largest plant (Orot Rabin) produces 2,600 MW.' },
  { date: '25/4 14:00', he: '🚨 מערכת הגנת חירום נותקה', en: '🚨 Emergency safety system disconnected', cat: 'warn',
    desc_he: 'הצוות מנתק ידנית את מערכת קירור החירום של הכור — מערכת בטיחות שמציפה את הליבה במים אם הקירור הראשי נכשל. הסיבה: לא להפריע לניסוי המתוכנן. זוהי הפרת רישיון תפעולי חמורה. הניסוי נדחה ב-9 שעות בגלל דרישות רשת החשמל.',
    desc_en: 'The crew manually disables the Emergency Core Cooling System (ECCS) — a safety system that floods the core with water if primary cooling fails. Reason: avoid interference with the planned test. This is a serious operating license violation. Test postponed 9 hours due to grid demands.' },
  { date: '26/4 00:28', he: '⚠ עוצמת הכור התרסקה', en: '⚠ Reactor power crashed', cat: 'warn',
    desc_he: 'מפעיל לחץ בטעות על מתג שגוי. עוצמת הכור התרסקה ל-1% מהרגיל. במצב זה מצטבר בכור גז קסנון רדיואקטיבי שדועך את התגובה הגרעינית. הצעד הבטוח היה לכבות את הכור ל-2-3 ימים. במקום זאת, הצוות שלף כמעט את כל מוטות הבקרה — נשארו רק 8 מתוך 211 — כדי להחזיר את העוצמה. הכור היה כעת חסר רוב הגנות הבטיחות שלו.',
    desc_en: 'An operator accidentally hit the wrong switch. Reactor power crashed to 1% of normal. In this state radioactive xenon gas accumulates in the core, suppressing the nuclear reaction. The safe action was to shut down for 2-3 days. Instead, the crew withdrew almost all control rods — only 8 of 211 remained — to restore power. The reactor was now stripped of most of its safety reserves.' },
  { date: '26/4 01:23:40', he: '🔴 הפיצוץ', en: '🔴 EXPLOSION', cat: 'disaster',
    desc_he: 'נלחץ כפתור עצירת החירום AZ-5 (לא ידוע בוודאות אם על ידי מפעיל או מערכת אוטומטית). אבל בגלל פגם בעיצוב המוטות — הקצה התחתון שלהן עשוי גרפיט שדוחף מים החוצה — הלחיצה גרמה דווקא לקפיצת עוצמה אדירה במקום לעצירה. תוך 7 שניות התרחשו שני פיצוצים שהרסו את יחידה 4: גג המתכת בן 1,000 הטונים נעקר, ולוח המגן הביולוגי המסיבי מעליו (משקל 2,000 טונים) נזרק לאוויר ונחת בזווית מעל הליבה. ליבת הכור נחשפה לאוויר הפתוח. הגרפיט שבליבה החל לבעור — שריפה שתימשך 9 ימים.',
    desc_en: 'AZ-5 emergency stop button was pressed (uncertain whether by operator or automatic system). But due to a control rod design flaw — graphite tips that displace water — the press caused a massive power surge instead of a shutdown. Within 7 seconds, two explosions destroyed Unit 4: the 1,000-ton metal roof was torn off, and the massive 2,000-ton biological shield plate above it was ejected and landed at an angle over the core. The reactor core was exposed to open air. The graphite in the core caught fire — a blaze that would burn for 9 days.' },
  { date: '26/4 01:28', he: 'הכבאים מגיעים — בלי הגנת קרינה', en: 'Firefighters arrive — no radiation protection', cat: 'response',
    desc_he: '14 כבאים בראשות הסגן ולדימיר פראביק מגיעים תוך פחות מ-5 דקות. הם חושבים שמדובר בשריפה רגילה של גג. אף אחד לא יידע אותם שיש קרינה רדיואקטיבית. אין להם מדי קרינה אישיים, אין להם בגדי הגנה מתאימים, אין להם מסכות. רובם ימותו תוך שבועות מתסמונת קרינה חריפה.',
    desc_en: '14 firefighters led by Lt. Vladimir Pravik arrive in less than 5 minutes. They believe it\'s a regular roof fire. No one tells them about the radiation. They have no personal dosimeters, no proper protective gear, no breathing apparatus. Most will die within weeks from acute radiation syndrome.' },
  { date: '26/4 05:00', he: 'שריפת הגג כובתה — אבל הליבה ממשיכה לבעור', en: 'Roof fire out — but core still burning', cat: 'response',
    desc_he: 'שריפות הגג והבניין כובו. אבל הליבה הגרפיטית עצמה ממשיכה לבעור בטמפרטורה של 2,500°C, ופולטת חומר רדיואקטיבי לאוויר. השריפה הזו תימשך תשעה ימים נוספים.',
    desc_en: 'Roof and building fires were extinguished. But the graphite core itself continues to burn at 2,500°C, releasing radioactive material into the air. This fire will continue for nine more days.' },
  { date: '27/4 14:00', he: 'פינוי פריפיאט — "חזרו תוך 3 ימים"', en: 'Pripyat evacuation — "Back in 3 days"', cat: 'evac',
    desc_he: '1,200 אוטובוסים מפנים את 49,000 תושבי פריפיאט תוך 3 שעות בלבד. ההודעה לתושבים: "קחו רק את הדרוש ביותר, חזרו תוך 3 ימים". איש לא חזר לעולם. העיר נטושה עד היום.',
    desc_en: '1,200 buses evacuate 49,000 Pripyat residents within just 3 hours. The announcement to residents: "Bring only what\'s essential, return in 3 days." Nobody ever returned. The city remains abandoned to this day.' },
  { date: '28/4', he: 'שבדיה מתריעה לעולם', en: 'Sweden alerts the world', cat: 'global',
    desc_he: 'עובדים בתחנת הכוח פורסמרק בשבדיה מזהים קרינה גבוהה על נעליהם. ההסתרה הסובייטית קורסת — העולם מגלה לראשונה שהתרחש אסון גרעיני. ברית המועצות נאלצת להודות.',
    desc_en: 'Workers at the Forsmark power plant in Sweden detect high radiation on their shoes. The Soviet cover-up collapses — the world learns for the first time that a nuclear disaster has occurred. The USSR is forced to admit it.' },
  { date: '2-10/5', he: 'מבצע הפלת חול ובורון מהאוויר', en: 'Air-drop operation: sand and boron', cat: 'response',
    desc_he: '5,000 טון של חול, חימר, עופרת ובורון מוטלים על הליבה הבוערת ב-1,800 גיחות מסוקים. החול לכיבוי, הבורון לעצירת התגובה הגרעינית. טייסי המסוקים סופגים מנות קרינה גבוהות. ב-2 באוקטובר 1986 מסוק Mi-8 מתרסק כשפגע בכבל של מגדל הקירור — הטייס נהרג.',
    desc_en: '5,000 tons of sand, clay, lead, and boron are dropped on the burning core in 1,800 helicopter sorties. Sand for fire suppression, boron to stop the nuclear reaction. Helicopter pilots absorb high radiation doses. On 2 October 1986, an Mi-8 helicopter crashed after hitting a cooling tower cable — the pilot was killed.' },
  { date: '4-6/5', he: 'שלושת המתנדבים — צוללים אל המים שמתחת', en: 'The Three Volunteers — diving below', cat: 'response',
    desc_he: 'שלושה מהנדסים — אלכסיי אננקו, ולרי בז׳פאלוב ובוריס בארנוב — צוללים למאגר המים שמתחת לכור הבוער. מטרתם: לפתוח שסתום ולנקז את המים, כדי למנוע פיצוץ קיטור משני שיכול היה להגדיל את האסון פי 10. בניגוד לאגדה הרווחת — שלושתם שרדו. אננקו ובז׳פאלוב חיים עד היום.',
    desc_en: 'Three engineers — Alexei Ananenko, Valeri Bezpalov, and Boris Baranov — dive into the water reservoir beneath the burning reactor. Their mission: open a valve to drain the water and prevent a secondary steam explosion that could have multiplied the disaster tenfold. Contrary to popular legend — all three survived. Ananenko and Bezpalov are alive today.' },
  { date: '6/5', he: 'שריפת הגרפיט הסתיימה', en: 'Graphite fire extinguished', cat: 'response',
    desc_he: 'אחרי 9 ימי בעירה, השריפה כובתה. כמות החומר הרדיואקטיבי שנפלטה לאוויר: פי 400 לערך מהפצצה האטומית של הירושימה.',
    desc_en: 'After 9 days of burning, the fire was extinguished. Total radiation released: 5,300 PBq — approximately 400 times the Hiroshima bomb in terms of radioactive material.' },
  { date: '5-11/1986', he: 'בניית הסרקופג הראשון', en: 'First Sarcophagus built', cat: 'build',
    desc_he: '600,000 ליקווידטורים בונים מבנה בטון ענק על הריסות הכור — "אובייקט מקלט", שכונה מאז "הסרקופג". הוקם תוך 6 חודשים בלבד. תוכנן לעמידות 30 שנה.',
    desc_en: '600,000 liquidators build a massive concrete structure over the reactor ruins — "Object Shelter", later called "the Sarcophagus". Erected in just 6 months. Designed for 30-year lifespan.' },
  { date: '1986-1989', he: 'מבצע "ביו-רובוטים" — חיילים על הגג', en: 'Operation Bio-Robots — soldiers on the roof', cat: 'response',
    desc_he: 'אחרי שרובוטים מתוצרת גרמניה ויפן נכשלו — האלקטרוניקה שלהם נשרפה מעוצמת הקרינה — 3,400 חיילים סובייטיים נשלחו לגג כל אחד למשך 40-90 שניות בלבד. כל חייל זרק 1-2 גושי גרפיט באת ורץ למטה. כינו אותם "ביו-רובוטים".',
    desc_en: 'After German and Japanese robots failed — their electronics burned out by radiation — 3,400 Soviet soldiers were sent to the roof for only 40-90 seconds each. Each soldier shoveled 1-2 chunks of graphite then ran back down. They were called "Bio-Robots".' },
  { date: '29/11/2016', he: 'הסגירה החדשה מוסטת על הסרקופג הישן', en: 'New Safe Confinement slid over old sarcophagus', cat: 'build',
    desc_he: 'מבנה מתכת ענק — הגדול בעולם מסוגו, גובה 108 מ׳, משקל 36,000 טון — הוסט ממקום הקמתו אל מעל לסרקופג הישן שהתיישן. תוכנן לעמידות של 100 שנה.',
    desc_en: 'A massive metal structure — the world\'s largest movable structure of its kind, 108m tall, 36,000 tons — was slid from its construction site over the deteriorating old sarcophagus. Designed for 100-year lifespan.' },
];

export const TL_CAT: Record<string, { c: string; he: string; en: string }> = {
  build: { c: '#94a3b8', he: 'בנייה', en: 'Construction' },
  warn: { c: '#f59e0b', he: 'אזהרה', en: 'Warning' },
  pre: { c: '#06b6d4', he: 'טרום-אסון', en: 'Pre-Disaster' },
  disaster: { c: '#dc2626', he: 'אסון', en: 'Disaster' },
  response: { c: '#22c55e', he: 'תגובה', en: 'Response' },
  evac: { c: '#a855f7', he: 'פינוי', en: 'Evacuation' },
  global: { c: '#06b6d4', he: 'גלובלי', en: 'Global' },
};

// =================== INSAG-7 — 10 STEPS (RBMK simulator) ===================
export const INSAG = [
  { time: '01:06', mood: 'normal',
    he: 'הצוות מתחיל להוריד את עוצמת הכור', en: 'Power drops for test',
    simple_he: 'הצוות מתחיל להוריד בהדרגה את עוצמת הכור — מ-100% ל-50% — לקראת ניסוי בטיחות שתוכנן 4 שנים מראש.',
    simple_en: 'Crew begins lowering reactor power from 100% to 50% in preparation for a safety test planned 4 years in advance.',
    pro_he: 'הורדה מבוקרת מ-3,200 מגה-וואט תרמיים ל-1,600 מגה-וואט. תוכנית הניסוי: לבדוק שכאשר התחנה מתנתקת מהרשת בעת תקלה, אנרגיית הסיבוב של הטורבינה (coastdown) יכולה לספק חשמל למשאבות הקירור הראשיות במשך כ-45 שניות — עד שגנרטורי הדיזל החירום מספיקים להתניע.',
    pro_en: 'Controlled reduction from 3,200 MWt to 1,600 MWt. Test plan: verify that when the plant disconnects from the grid during a failure, turbine inertia (coastdown) can power the main circulation pumps for ~45 seconds — until emergency diesels start.' },
  { time: '14:00', mood: 'normal',
    he: 'מערכת קירור חירום מנותקת ידנית', en: 'Emergency cooling disconnected',
    simple_he: 'הצוות מנתק ידנית מערכת בטיחות חיונית — מערכת קירור החירום של הכור — כדי שלא תפריע לניסוי. זוהי הפרת רישיון תפעולי.',
    simple_en: 'The crew manually disconnects a critical safety system — the Emergency Core Cooling System — to prevent it from interfering with the test. This was a license violation.',
    pro_he: 'מערכת קירור החירום (ECCS) מנותקת ידנית, רשמית מסיבת "מניעת הפעלה לא רצויה במהלך הניסוי". מדובר בהפרה בולטת של תקנון התפעול. רגולטור רשת החשמל האוקראיני דורש המשך אספקת חשמל לרשת — והניסוי נדחה ב-9 שעות.',
    pro_en: 'ECCS manually disabled, officially citing "prevention of unwanted activation during the test." Major operating license violation. The Ukrainian grid regulator demands continued power supply — test postponed 9 hours.' },
  { time: '23:10', mood: 'caution',
    he: 'משמרת לילה מקבלת את הניסוי — בלי הכשרה', en: 'Night shift receives test — without training',
    simple_he: 'בעקבות הדחייה, המשמרת המקורית שהוכשרה לניסוי כבר חזרה הביתה. המשמרת החדשה — שאמורה לבצע ניסוי מורכב של 4 שנות תכנון — לא תודרכה. המפעיל הראשי הוא בחור עם ארבעה חודשי ניסיון בלבד.',
    simple_en: 'Due to the delay, the original shift trained for the test already went home. The new shift — expected to perform a complex test that was 4 years in planning — was not briefed. The senior operator is a young man with only 4 months of experience.',
    pro_he: 'משמרת היום (סוקולוב) שתודרכה על תוכנית הניסוי כבר חזרה הביתה. משמרת לילה תחת מהנדס ראשי אנטולי דיאטלוב מקבלת תוכנית ניסוי מורכבת ללא הכשרה מסודרת. המפעיל הראשי לאוניד טופטונוב — בעל ניסיון של 4 חודשים בלבד בתחנה.',
    pro_en: 'Day shift (Sokolov) trained for test program had returned home. Night shift under chief engineer Anatoly Dyatlov receives complex test plan without proper briefing. Senior operator Leonid Toptunov — only 4 months\' experience.' },
  { time: '00:28', mood: 'danger',
    he: 'עוצמת הכור התרסקה — והכור "הורעל"', en: 'Power crashed — reactor "poisoned"',
    simple_he: 'בגלל לחיצה שגויה על מתג, עוצמת הכור התרסקה ל-1% מהרגיל. במצב הזה הכור מייצר באופן טבעי גז רדיואקטיבי בשם קסנון, שדועך את התגובה הגרעינית — תופעה שנקראת "הרעלת קסנון". הצעד הבטוח: לכבות לגמרי ל-2-3 ימים. אבל המהנדס הראשי דיאטלוב מצווה: "להחזיר את העוצמה!" — בניגוד לתקנות.',
    simple_en: 'Due to wrong switch press, reactor power crashed to 1% of normal. In this state, the reactor naturally produces radioactive xenon gas that suppresses the nuclear reaction — a phenomenon called "xenon poisoning". Safe step: shut down completely for 2-3 days. But chief engineer Dyatlov orders: "Bring power back up!" — against regulations.',
    pro_he: 'טופטונוב לחץ בטעות על מתג מקומי-לאוטומטי. ההספק קרס מ-1,600 ל-30 מגה-וואט. במצב זה איזוטופ קסנון-135 — סופח הניוטרונים החזק ביותר הידוע, נוצר מיוד-135 שהוא תוצר ביקוע נפוץ — מצטבר ומדכא את הליבה. בכור פעיל בעוצמה רגילה, הקסנון בולע ניוטרון והופך לקסנון-136 לא רעיל. אופציה בטוחה: כיבוי 2-3 ימים עד פירוק הקסנון. דיאטלוב מתעקש: "להעלות את ההספק!" — בניגוד לתקנון.',
    pro_en: 'Toptunov accidentally hit local-to-auto switch. Power crashed from 1,600 to 30 MWt. In this state Xe-135 — the strongest known neutron absorber, produced from I-135 (a common fission product) — accumulates and chokes the core. In an active reactor at normal power, xenon absorbs a neutron becoming non-toxic Xe-136. Safe option: shut down 2-3 days for xenon decay. Dyatlov insists: "Bring power back up!" — against regulations.' },
  { time: '01:00', mood: 'danger',
    he: 'מוטות הבטיחות נשלפים בכוח — נשארו רק 8 מתוך 211', en: 'Safety rods withdrawn — only 8 of 211 remain',
    simple_he: 'הצוות שולף ידנית את מוטות הבקרה — אלה שמכניסים לכור כדי לעצור או להאט את התגובה הגרעינית. מתוך 211 המוטות, נשארו בכור רק 8. התקנון דורש מינימום 30 מוטות. הכור נשאר כמעט ללא יכולת בלימה.',
    simple_en: 'The crew manually withdraws control rods — those inserted into the reactor to stop or slow the nuclear reaction. Of 211 rods, only 8 remain in the core. Regulations require minimum 30 rods. The reactor is left almost without ability to halt power rise.',
    pro_he: 'מתוך 211 מוטות בקרה, רק 8 נותרו בליבה (ORM=8). מינימום מותר על פי תקנון: 30 מוטות (≈1.5β רזרבה תגובתיות). בלי מוטות בליבה, אין יכולת חוצץ לעצור עליית הספק. ההספק מתייצב סביב 200 מגה-וואט — מצב לא יציב.',
    pro_en: 'Of 211 control rods, only 8 remain in core (ORM=8). Regulatory minimum: 30 rods (≈1.5β reactivity reserve). Without rods in core, no buffer to halt power rise. Power stabilizes around 200 MWt — unstable state.' },
  { time: '01:23:04', mood: 'critical',
    he: 'הניסוי מתחיל', en: 'Test begins',
    simple_he: 'הניסוי מתחיל. הקיטור לטורבינה מנותק והיא מתחילה להאט. בו-זמנית גם משאבות הקירור מתחילות להאט. זרימת המים לכור פוחתת ובועות קיטור מתחילות להיווצר בערוצי הקירור.',
    simple_en: 'Test begins. Steam to the turbine is cut, and it begins to slow down. Simultaneously, the cooling pumps begin to slow as well. Water flow to the reactor decreases, and steam bubbles begin forming in the cooling channels.',
    pro_he: 'שסתום הקיטור לטורבוגנרטור 8 נסגר — מתחיל coastdown. 4 משאבות קירור ראשיות (MCP) מואטות יחד עם הטורבינה. זרימת המים לליבה יורדת. בועות קיטור (voids) מתחילות להיווצר בתוך 1,661 ערוצי הקירור.',
    pro_en: 'Steam valve to turbogenerator 8 closes — coastdown begins. 4 Main Circulation Pumps (MCPs) slow with turbine. Water flow to core decreases. Steam voids begin forming in 1,661 cooling channels.' },
  { time: '01:23:40', mood: 'explosion',
    he: 'כפתור עצירת החירום נלחץ — והפך לקטליזטור', en: 'Emergency stop pressed — became the trigger',
    simple_he: 'נלחץ כפתור עצירת החירום. כפתור שאמור היה לעצור את הכור תוך שניות — אבל בגלל פגם בעיצוב מוטות הבקרה (קצה תחתון מגרפיט שדוחף מים החוצה), הלחיצה גורמת דווקא לקפיצה אדירה בעוצמה. תוך שנייה וחצי הכור עובר למצב לא נשלט.',
    simple_en: 'The emergency stop button is pressed. A button that should have stopped the reactor within seconds — but due to a control rod design flaw (graphite tip displacing water as rods enter), the press actually causes a massive power surge. Within 1.5 seconds the reactor goes uncontrollable.',
    pro_he: 'כפתור AZ-5 נלחץ — מתחילה החדרת כל 211 המוטות. מקור הלחיצה לא ידוע בוודאות (החלטת אקיימוב/טופטונוב או מערכת בטיחות אוטומטית). הקצוות הגרפיטיים של המוטות (3 מ׳ עליונים) דוחפים מים החוצה תחילה — מייצרים תוספת תגובתיות חיובית במקום שלילית. בליבה ריקה ב-ORM=8 ועם בועות רבות (מקדם חללות חיובי +4.7β), הכור עובר לקריטיות פרומפטית בתוך 1.5 שניות.',
    pro_en: 'AZ-5 pressed — all 211 rods begin insertion. Source of press uncertain (Akimov/Toptunov decision or auto safety). Rods\' graphite tips (upper 3m) displace water first — generating positive instead of negative reactivity. With core depleted to ORM=8 and high voiding (+4.7β positive void coefficient), reactor goes prompt-critical within 1.5 seconds.' },
  { time: '01:23:43', mood: 'apocalypse',
    he: 'העוצמה זינקה לפי 100 מהרגיל', en: 'Power surged 100× normal',
    simple_he: 'תוך 3 שניות הכור מייצר פי 100 מהעוצמה הנורמלית שלו. זוהי תגובת שרשרת בלתי נשלטת — שלא ניתנת לעצירה. הדלק הגרעיני מתחיל להימס, צינורות הקירור קורסים, לחץ הקיטור מזנק.',
    simple_en: 'Within 3 seconds the reactor produces 100× its normal power. This is an uncontrolled chain reaction — unstoppable. The nuclear fuel begins to melt, cooling tubes collapse, steam pressure surges.',
    pro_he: 'ההספק עולה אקספוננציאלית: 200 → 530 → מעל 30,000 מגה-וואט. דלק האורניום נמס. תעלות הלחץ מסגסוגת זירקאלוי קורסות. לחץ הקיטור ב-1,661 ערוצים זינק מ-65 אטמוספרות לְמעל 600. הפיצוץ הראשון: התפוצצות קיטור ב-01:23:45.',
    pro_en: 'Power rises exponentially: 200 → 530 → 30,000+ MWt. Uranium fuel melts. Zircaloy pressure tubes collapse. Steam pressure in 1,661 channels surges from 65 atm to >600 atm. First explosion: steam blast at 01:23:45.' },
  { time: '01:23:45', mood: 'apocalypse',
    he: 'הפיצוץ הראשון — קיטור', en: 'First explosion — Steam',
    simple_he: 'הפיצוץ הראשון, ככל הנראה התפוצצות לחץ קיטור עצומה. גג המתכת בן 1,000 הטונים נעקר ונזרק לאוויר. צינורות הקירור נחתכים. אוויר חודר לליבה הלוהטת (2,500°C) ומגיב עם המתכת — מייצר גז מימן.',
    simple_en: 'The first explosion — most likely a massive steam pressure burst. The 1,000-ton metal roof is torn off and ejected. Cooling tubes are severed. Air enters the burning core (2,500°C) and reacts with the metal — generating hydrogen gas.',
    pro_he: 'פיצוץ ראשון — שתי תיאוריות: (1) פיצוץ קיטור מאידוי כל מי הקירור הקיימים בליבה. (2) פיצוץ נוקלאו-תרמי. גג של ~1,000 ט׳ + מגן עליון "סכמה E" של 2,000 ט׳ נזרקים. תעלות הלחץ נחתכות. אוויר חודר לליבה ופוגש זירקאלוי חם ב-2,500°C. תגובה: Zr+H₂O → ZrO₂+H₂ — מייצרת מימן.',
    pro_en: 'First explosion — two theories: (1) Steam explosion from vaporization of all coolant in core. (2) Nuclear-thermal explosion. ~1,000 t roof + 2,000 t "Schema E" upper bio-shield ejected. Pressure tubes severed. Air enters core, meeting hot Zircaloy at 2,500°C. Reaction: Zr+H₂O → ZrO₂+H₂ — generates hydrogen.' },
  { time: '01:23:47', mood: 'apocalypse',
    he: 'הפיצוץ השני — מימן', en: 'Second explosion — Hydrogen',
    simple_he: 'שתי שניות אחרי הראשון — פיצוץ שני, חזק יותר, של גז המימן שנוצר. הליבה נחשפת לחלוטין לאוויר. כ-7 טונים של דלק רדיואקטיבי מועפים לשמיים. הגרפיט שבליבה נדלק במגע עם החמצן — שריפה שתימשך 9 ימים. סך כמות החומר הרדיואקטיבי שישתחרר: כ-400 פעמים מה ששחררה הפצצה האטומית בהירושימה. תוך שעות יאובחנו 134 ליקווידטורים בתסמונת קרינה חריפה.',
    simple_en: 'Two seconds after the first — a second, stronger explosion of the hydrogen gas that formed. The core is fully exposed. About 7 tons of radioactive fuel are blown skyward. The graphite ignites on contact with oxygen — a fire that will burn for 9 days. Total radioactive material to be released: about 400× the Hiroshima atomic bomb. Within hours, 134 liquidators will be diagnosed with acute radiation syndrome.',
    pro_he: '2 שניות אחרי הראשון — פיצוץ שני, ככל הנראה התפוצצות מימן/חמצן. הליבה נפתחת לחלוטין. ~7 טון דלק מועפים לאטמוספירה. גרפיט במגע עם אוויר ב-2,500°C מתלקח — שריפה שתימשך 9 ימים. שחרור 5,300 פטה-בקרל של תוצרי ביקוע. 134 ליקווידטורים מאובחנים בתסמונת קרינה חריפה (ARS) חמורה תוך שעות.',
    pro_en: '2 seconds after the first — second blast, likely hydrogen/oxygen explosion. Core fully opens. ~7 tons of fuel ejected to atmosphere. Graphite ignites in air at 2,500°C — fire that will burn 9 days. Release of 5,300 PBq fission products. 134 liquidators diagnosed with severe ARS within hours.' },
];

// =================== RBMK COMPONENTS ===================
export const RBMK_COMP = [
  { id: 'vessel', he: 'מכל לחץ — מבנה הכור', en: 'Pressure Vessel',
    simple_he: 'הקופסה החיצונית שעוטפת את הכור. בכורי RBMK הסובייטיים — בניגוד לכורים מערביים — לא הייתה כיפת בטון נוספת מסביב. זה היה כשל תכנון מהותי.',
    simple_en: 'The outer box wrapping the reactor. In Soviet RBMK reactors — unlike Western ones — there was no additional concrete dome around it. A fundamental design failure.',
    pro_he: 'מכל פלדה-בטון בגודל 26 מ׳ × 21.6 מ׳. ב-RBMK חסר מבנה הכלה (containment) חיצוני. בכורים מערביים מסוג PWR/BWR יש כיפת בטון נוספת המסוגלת לעמוד בהשתחררות מלאה של דלק. זה היה כשל תכן קריטי.',
    pro_en: 'Steel-concrete vessel 26m × 21.6m. RBMK lacks outer containment. Western PWR/BWR have additional concrete dome capable of withstanding full release. Critical design flaw.' },
  { id: 'graphite', he: 'גרפיט — ליבת הכור', en: 'Graphite Moderator',
    simple_he: '1,700 טונים של בלוקי גרפיט (אותו חומר כמו בקצה של עפרון) שמרכיבים את ליבת הכור. הגרפיט מאט את הניוטרונים כדי שיוכלו לפצל את האורניום. בעירה של גרפיט בטמפרטורה גבוהה היא שגרמה לפליטת הרדיואקטיביות לאורך 9 ימים.',
    simple_en: '1,700 tons of graphite blocks (same material as pencil tips) make up the reactor core. Graphite slows neutrons so they can split uranium atoms. Burning graphite at high temperature is what caused 9 days of radioactive emissions.',
    pro_he: '1,700 טון גרפיט יוצרים את הליבה הקובית. תפקיד: מאט (moderator) של ניוטרונים. בעל מקדם תגובתיות חיובי בטמפרטורה גבוהה. בעירה ב-2,500°C במגע עם אוויר היא ששחררה את רוב הצסיום-137 לאורך תקופת השריפה.',
    pro_en: '1,700 tons of graphite forming cubic core. Functions as moderator. Has positive temperature reactivity coefficient. Combustion at 2,500°C with air released most Cs-137 over the burning period.' },
  { id: 'fuel', he: 'מוטות הדלק — מקור התגובה הגרעינית', en: 'Fuel Rods',
    simple_he: 'מוטות אורניום — 1,661 מהם בליבה. כל מוט באורך 7 מטרים. סך כל האורניום בכור: 192 טונים. בפיצוץ — בערך 7 טונים מהדלק עפו לאוויר. זו הייתה הפעם הראשונה בהיסטוריה שכור פעיל התפוצץ.',
    simple_en: 'Uranium rods — 1,661 of them in the core. Each rod is 7 meters long. Total uranium in the reactor: 192 tons. In the explosion — about 7 tons of fuel were thrown into the air. This was the first time in history an operating reactor exploded.',
    pro_he: 'דלק UO₂ מועשר ב-2.0% U-235. 1,661 ערוצי דלק. אורך מוט: 7 מ׳. תכולת אורניום בליבה: 192 טון. בפיצוץ: ~7 טון דלק נפלט לאטמוספירה — הראשונה בהיסטוריה של פיצוץ כור פעיל.',
    pro_en: 'UO₂ fuel enriched to 2.0% U-235. 1,661 fuel channels. Rod length: 7m. Core uranium: 192 tons. In explosion: ~7 tons fuel ejected to atmosphere — first in history of operating reactor explosion.' },
  { id: 'rods', he: 'מוטות הבקרה — והפגם הקטלני', en: 'Control Rods — the Fatal Flaw',
    simple_he: '211 מוטות עשויים בורון, שמחדירים לליבה כדי להאט או לעצור את התגובה הגרעינית. הפגם: הקצה התחתון של המוטות עשוי גרפיט (3 מ׳ באורך). כשמכניסים אותם לכור, הגרפיט נכנס ראשון ודוחף את המים החוצה — מה שדווקא מאיץ את התגובה. בכורים מערביים החדרה לוקחת 3 שניות. ב-RBMK 18-21 שניות. זה הפגם שהפך את כפתור עצירת החירום לקטליזטור של הפיצוץ.',
    simple_en: '211 rods made of boron, inserted into the core to slow or stop the nuclear reaction. The flaw: the lower tip of each rod is graphite (3 meters long). When inserted, the graphite enters first and pushes water out — which actually accelerates the reaction. In Western reactors insertion takes 3 seconds. In RBMK, 18-21 seconds. This is the flaw that turned the emergency stop button into the trigger of the explosion.',
    pro_he: '211 מוטות B₄C/Dy₂TiO₅. החדרה מלאה לוקחת 18-21 שניות (לעומת ~3 שניות בכורים מערביים). פגם קריטי: קצה תחתון של 3 מ׳ (במקור 4.5 מ׳) גרפיט מקטין את הספיחה לפני שספח הבורון מגיע — "אפקט החדרה חיובי" שגרם לפיצוץ.',
    pro_en: '211 B₄C/Dy₂TiO₅ rods. Full insertion: 18-21 sec (vs ~3 sec in Western reactors). Critical flaw: 3m graphite tip (originally 4.5m) reduces absorption before boron absorber arrives — "positive scram effect" that triggered explosion.' },
  { id: 'drum', he: 'תופי הפרדת קיטור', en: 'Steam Separator Drums',
    simple_he: '4 גלילים אופקיים גדולים (30 מ׳ אורך) שמפרידים את הקיטור מהמים אחרי שעברו דרך הכור. הקיטור הולך לטורבינה לייצור חשמל, המים חוזרים לכור.',
    simple_en: '4 large horizontal cylinders (30m long) that separate steam from water after passing through the reactor. Steam goes to the turbine to generate electricity, water returns to the reactor.',
    pro_he: '4 גלילים אופקיים, 30 מ׳ × 2.6 מ׳. הפרדה גרביטציונית (בעזרת כוח כובד) של תערובת מים-קיטור (14% קיטור) ל: קיטור יבש לטורבינה, מים בחזרה דרך משאבות הקירור הראשיות לליבה. לחץ פעולה: 65 אטמוספרות.',
    pro_en: '4 horizontal drums, 30m × 2.6m. Gravimetric separation of steam-water mixture (14% steam) into: dry steam to turbine, water back through MCPs to core. Operating pressure: 65 atm.' },
  { id: 'mcp', he: 'משאבות הקירור הראשיות', en: 'Main Circulation Pumps',
    simple_he: '8 משאבות גדולות שמזרימות מים דרך הכור לקירור. בדרך כלל פועלות 6 בלבד, ו-2 ברזרבה. ב-26 באפריל הצוות הפעיל את כל ה-8 בו-זמנית — מה שלא היה מומלץ והגביר את הסכנה.',
    simple_en: '8 large pumps that circulate water through the reactor for cooling. Normally only 6 operate, with 2 in reserve. On 26 April the crew ran all 8 simultaneously — which was not recommended and increased the danger.',
    pro_he: '8 משאבות צנטריפוגליות, 6 פעילות + 2 רזרבה. ב-26/4 כל ה-8 הופעלו לדרישת הניסוי. זרימה מוגברת הקטינה את ההפרש בין כניסה ליציאה (subcooling), הגדילה רגישות למקדם החללות.',
    pro_en: '8 centrifugal pumps, 6 active + 2 reserve. On 26/4 all 8 operated per test requirement. Increased flow reduced inlet-outlet differential (subcooling), increased sensitivity to void coefficient.' },
  { id: 'turbine', he: 'הטורבינה והגנרטור', en: 'Turbogenerator',
    simple_he: 'מתקן שממיר את הקיטור החם מהכור לחשמל. הניסוי ב-26 באפריל היה אמור לבדוק האם הטורבינה הזו, גם בזמן שהיא נעצרת בעקבות תקלה, יכולה להמשיך לספק חשמל למשאבות הקירור במשך הדקה הקריטית עד שגנרטורי הדיזל יתחילו לעבוד.',
    simple_en: 'A device converting the hot steam from the reactor into electricity. The test on 26 April was supposed to verify whether this turbine, even while shutting down due to a failure, could continue supplying power to the cooling pumps during the critical minute until backup diesel generators come online.',
    pro_he: '2 טורבוגנרטורים מסוג K-500-65/3000, 500 מגה-וואט חשמליים כל אחד. ניסוי 26/4 בחן את יכולת ה-coastdown של גנרטור 8 לאספקת חשמל למשאבות הקירור למשך 45 שניות עד שגנרטורי דיזל החירום עולים.',
    pro_en: '2 K-500-65/3000 turbogenerators, 500 MWe each. Test on 26/4 verified generator 8 coastdown capability to supply MCPs for 45 sec until emergency diesels online.' },
  { id: 'az5', he: 'כפתור עצירת החירום (AZ-5)', en: 'AZ-5 — Emergency Stop',
    simple_he: 'כפתור אדום של עצירת חירום. בכור תקין הוא היה אמור לעצור את הכור תוך שניות. בצ׳רנוביל, בגלל פגם תכנון של מוטות הבקרה, הלחיצה עליו ב-26 באפריל בשעה 01:23:40 גרמה דווקא לפיצוץ.',
    simple_en: 'A red emergency stop button. In a properly designed reactor, it should stop the reactor within seconds. At Chernobyl, due to a control rod design flaw, pressing it on 26 April at 01:23:40 actually triggered the explosion.',
    pro_he: 'AZ-5 (Avariynaya Zashchita-5) — מערכת עצירת חירום שמחדירה את כל 211 המוטות. ב-26/4 בשעה 01:23:40 הלחיצה עליו גרמה ל"אפקט החדרה חיובי" בכור עם ORM=8 ומקדם חללות גבוה. הכור הפך לסופר-קריטי פרומפטי תוך 1.5 שניות.',
    pro_en: 'AZ-5 (Avariynaya Zashchita-5) — emergency shutdown inserting all 211 rods. On 26/4 01:23:40 the press triggered "positive scram effect" in core with ORM=8 and high void coefficient. Reactor went prompt supercritical within 1.5 seconds.' },
  { id: 'eccs', he: 'מערכת קירור החירום', en: 'Emergency Core Cooling System',
    simple_he: 'מערכת בטיחות שמציפה את הכור במים אם הקירור הראשי נכשל. ב-25 באפריל בשעה 14:00 — שעות לפני הניסוי — הצוות ניתק אותה ידנית כדי שלא תפריע לניסוי. זוהי הפרת רישיון תפעולי בולטת.',
    simple_en: 'A safety system that floods the reactor with water if primary cooling fails. On 25 April at 14:00 — hours before the test — the crew manually disconnected it to prevent interference with the test. A blatant license violation.',
    pro_he: 'מערכת ECCS — מציפה את הליבה במים אם זרימת הקירור הראשית נופלת מתחת ל-50%. ב-25/4 14:00 דיאטלוב הורה לנתק אותה כדי לא להפריע לניסוי. הפרת רישיון תפעולי בולטת.',
    pro_en: 'ECCS — floods core with water if primary cooling drops below 50%. On 25/4 14:00 Dyatlov ordered disconnect to not interfere with test. Major operating license violation.' },
  { id: 'shield', he: 'לוח המגן הביולוגי העליון', en: 'Upper Bio-Shield',
    simple_he: 'לוח פלדה-בטון בקוטר 17 מטר, עובי 3 מטר, ומשקל 2,000 טון — שאמור היה לאטום את החלק העליון של הכור מקרינה. בפיצוץ הוא נזרק לאוויר ונחת בזווית של 15 מעלות מעל הליבה החשופה. הוא נשאר ככה עד היום, נצפה בתמונות לוויין.',
    simple_en: 'A steel-concrete plate, 17m diameter, 3m thick, 2,000 tons — meant to seal the reactor top from radiation. In the explosion it was thrown into the air and landed at a 15-degree angle over the exposed core. It remains so to this day, visible from satellite imagery.',
    pro_he: 'לוח עליון מסיבי בקוטר 17 מ׳, עובי 3 מ׳, משקל 2,000 ט׳. אמור היה לאטום את הליבה. בפיצוץ הראשון נזרק לאוויר עם מערך תעלות הלחץ. נחת בזווית של ~15° מעל הליבה החשופה — נשאר כך עד היום.',
    pro_en: 'Massive upper plate 17m diameter, 3m thick, 2,000 t. Should have sealed core. In first explosion ejected with pressure tube cascade. Landed at ~15° over exposed core — remains so today.' },
  { id: 'void', he: 'הפגם הפיזיקלי הגדול ביותר', en: 'The Greatest Physical Flaw',
    simple_he: 'תכונה פיזיקלית של כור RBMK: כשמים מתאדים לקיטור בתוך הכור, התגובה הגרעינית מתחזקת במקום להחליש. ברוב הכורים בעולם זה הפוך — וזהו מנגנון בטיחות מובנה. ב-RBMK המים שימשו רק לקירור, והגרפיט הוא שמאט את הניוטרונים. כשמים מתחלפים בקיטור, פחות ניוטרונים נספגים והתגובה מתעצמת. בועה → חום נוסף → יותר קיטור → תגובת שרשרת חיובית. זה היה הפגם הקטלני ביותר.',
    simple_en: 'A physical property of RBMK reactors: when water vaporizes to steam inside the reactor, the nuclear reaction strengthens instead of weakening. In most reactors it\'s the opposite — a built-in safety mechanism. In RBMK, water served only as coolant, and graphite is what slows neutrons. When water becomes steam, fewer neutrons are absorbed and the reaction intensifies. Bubble → more heat → more steam → positive feedback loop. This was the most lethal flaw.',
    pro_he: 'מקדם תגובתיות חללות חיובי של +4.7β ב-RBMK. בכורי מים-מאט מערביים (PWR/BWR) — מים גם מאט וגם קירור: כשמים מתאדים → פחות מאט → תגובה יורדת → בטיחות מובנית. ב-RBMK הגרפיט הוא המאט והמים רק קירור (וסופחים ניוטרונים מעט). כשמים מתאדים → פחות ספיחה → תגובתיות עולה → טמפרטורה עולה → יותר קיטור → רגרסיה חיובית קטלנית.',
    pro_en: 'Positive void reactivity coefficient of +4.7β in RBMK. In Western water-moderated reactors (PWR/BWR), water serves as both moderator and coolant. In RBMK, graphite is moderator and water only coolant — fatal positive feedback.' },
  { id: 'orm', he: 'רזרבת מוטות הבקרה', en: 'Operational Reactivity Margin',
    simple_he: 'מספר מוטות הבקרה שצריכים תמיד להישאר בליבה כרזרבה בטיחותית — כך שתמיד יהיה אפשר לעצור את הכור במהירות. המינימום שמותר על פי תקנון: 30 מוטות. ב-26 באפריל בשעה 01:23:40 — בעת הפיצוץ — היו רק 8 מוטות בליבה. כמעט ללא הגנה.',
    simple_en: 'The number of control rods that must always remain in the core as a safety reserve — so that the reactor can always be stopped quickly. Regulatory minimum: 30 rods. On 26 April at 01:23:40 — at the moment of the explosion — only 8 rods were in the core. Almost without protection.',
    pro_he: 'ORM — מספר המוטות הזמינים להחדרה לעצירת תגובתיות. מינימום על פי תקנון: 30 מוטות (≈1.5β). ב-01:23:40 הליבה הייתה ב-ORM=8 — כמעט ללא רזרבה. גורם מכריע לאסון.',
    pro_en: 'ORM — number of rods available for reactivity insertion. Regulatory minimum: 30 rods (≈1.5β). At 01:23:40 core was at ORM=8 — nearly no reserve. Decisive disaster factor.' },
  { id: 'diesel', he: 'גנרטורי הדיזל לחירום', en: 'Emergency Diesel Generators',
    simple_he: '3 גנרטורי דיזל פנימיים שאמורים לספק חשמל למשאבות הקירור אם החשמל לכור נופל. הבעיה: לוקח להם בערך דקה להתניע. בדיוק את הדקה הזו ניסוי הטורבינה ב-26 באפריל ניסה לגשר עליה — באמצעות אנרגיית הסיבוב של הטורבינה. שלושה ניסויים קודמים נכשלו (1982-1985). הניסוי הרביעי הוא שגרם לאסון.',
    simple_en: '3 internal diesel generators meant to supply power to cooling pumps if reactor power drops. The problem: it takes them about a minute to start. The turbine test on 26 April was specifically designed to bridge that minute — using the turbine\'s rotational inertia. Three previous tests had failed (1982-1985). The fourth test is what caused the disaster.',
    pro_he: '3 גנרטורי דיזל בתוך מתחם הכור. תפקיד: לספק חשמל למשאבות הקירור (MCP) במקרה אובדן זרם חיצוני. אבל זמן ההתנעה ~60 שניות. רעיון ניסוי הטורבינה: להשתמש באנרגיית ההתמדה של הטורבינה לגשר על הפער — להפעיל את ה-MCP על ידי גנרטור-טורבינה בעת coastdown. 3 ניסויים קודמים נכשלו (1982-1985). הניסוי הרביעי גרם לאסון.',
    pro_en: '3 diesel generators inside reactor compound. Purpose: supply power to MCPs in case of external power loss. Startup time ~60 seconds. Turbine test idea: use turbine kinetic inertia to bridge the gap. 3 previous tests failed (1982-1985).' },
  { id: 'xenon', he: 'הרעלת קסנון — הכור "חונק את עצמו"', en: 'Xenon Poisoning — Reactor "Chokes Itself"',
    simple_he: 'בתוך הכור נוצר באופן טבעי גז קסנון-135. במצב פעולה רגיל הוא "נשרף" כל הזמן ולא מצטבר. אבל בעוצמה נמוכה הוא מצטבר ובולע ניוטרונים — מדכא את הכור. ב-26 באפריל אחרי קריסת העוצמה, הקסנון הצטבר וגרם להמשך הקריסה. הצעד הבטוח: לכבות 2-3 ימים ולתת לקסנון להתפרק. במקום זה הצוות שלף את המוטות בכוח.',
    simple_en: 'Inside the reactor, xenon-135 gas naturally forms. In normal operation it constantly "burns up" and doesn\'t accumulate. But at low power it accumulates and absorbs neutrons — suppressing the reactor. On 26 April after the power crash, xenon built up and caused further crash. The safe step: shut down for 2-3 days and let xenon decay. Instead the crew forcibly withdrew rods.',
    pro_he: 'תוצר ביקוע נפוץ של U-235: יוד-135 → דעיכת בטא → קסנון-135 (זמן מחצית-חיים 9.2 שעות). הוא ספיח הניוטרונים החזק ביותר הידוע. בכור פעיל בהספק רגיל: Xe-135 + ניוטרון → Xe-136 (לא רעיל, יציב) — מאזן צריכה. בהספק נמוך: Xe-135 מצטבר. ב-26/4 הצטברות הקסנון מ-23:10-00:28 גרמה לקריסת ההספק.',
    pro_en: 'Common fission product of U-235: Iodine-135 → beta decay → Xenon-135 (half-life 9.2 hours). Strongest known neutron absorber. In active reactor: Xe-135 + neutron → Xe-136 (non-toxic, stable). At low power: Xe-135 accumulates. On 26/4 xenon buildup from 23:10 to 00:28 caused power crash.' },
];

// =================== LIQUIDATOR GROUPS ===================
export const LIQUIDATORS = [
  { id: 'fire', icon: '🚒', he: 'הכבאים הראשונים', en: 'First Firefighters', count: '~30',
    lead: 'הסגן ולדימיר פראביק · הסגן ויקטור קיבנוק',
    desc_he: '14 כבאים שהגיעו ב-01:28 בלילה — תוך 5 דקות מהפיצוץ — ועוד שתי משמרות שהצטרפו אחר כך. הם הגיעו לזירה ללא הגנה מקרינה כי לא הודיעו להם על הקרינה. רובם מתו תוך שבועות ספורים מתסמונת קרינה חריפה בבית חולים מס׳ 6 במוסקבה. פראביק וקיבנוק שניהם זכו לאחר מותם בתואר "גיבור ברית המועצות".',
    desc_en: '14 firefighters who arrived at 01:28 at night — within 5 minutes of the explosion — plus two more shifts that joined later. They arrived without radiation protection because they were not informed of the radiation. Most died within just weeks from acute radiation syndrome at Hospital No. 6 in Moscow. Pravik and Kibenok both received "Hero of the Soviet Union" posthumously.',
    risk: 'extreme', dose: '4-16 גריי' },
  { id: 'pilot', icon: '🚁', he: 'טייסי המסוקים', en: 'Helicopter Pilots', count: '~600',
    lead: 'אלוף-משנה ניקולאי אנטושקין',
    desc_he: 'בוצעו 1,800 גיחות מסוק להפלת חול, חימר, עופרת ובורון על הליבה הבוערת. הקרינה במרחב מעל הכור הגיעה ל-3,500 רנטגן לשעה — עוצמה קטלנית בתוך דקות. טייס אחד נהרג ב-2 באוקטובר 1986 כשמסוק Mi-8 התרסק לאחר שכבל של מגדל הקירור פגע בלהבי הרוטור.',
    desc_en: '1,800 helicopter sorties to drop sand, clay, lead, and boron on the burning core. Radiation above the reactor reached 3,500 R/hr — fatal levels within minutes. One pilot was killed on 2 October 1986 when an Mi-8 crashed after a cooling tower cable struck the rotor blades.',
    risk: 'extreme', dose: '0.5-2 סיברט' },
  { id: 'tunnel', icon: '⛏', he: 'חופרי המנהרה מתחת לכור', en: 'Tunnel Diggers', count: '~400',
    lead: 'כורים מאזור הדונבאס וטולה',
    desc_he: 'כורים סובייטיים חפרו מנהרה באורך 168 מטר מתחת לליבה הבוערת — דרך אדמה רוויית קרינה — כדי להתקין מערכת קירור שתמנע מסת הליבה המותכת לחדור למי התהום ולזהם את כל אגן הדנייפר. עבדו 24 שעות ביממה במשמרות של 3 שעות בלבד בגלל חום ומנות קרינה.',
    desc_en: 'Soviet miners dug a 168-meter tunnel beneath the burning core — through radiation-saturated earth — to install a cooling system that would prevent the molten core mass from penetrating the groundwater and contaminating the entire Dnieper basin. Worked 24/7 in shifts of just 3 hours due to heat and radiation doses.',
    risk: 'high', dose: '~0.3 סיברט בממוצע' },
  { id: 'volunt', icon: '🏊', he: 'שלושת המתנדבים', en: 'Three Volunteers', count: '3',
    lead: 'אלכסיי אננקו · ולרי בז׳פאלוב · בוריס בארנוב',
    desc_he: 'ב-4-6 במאי שלושה מהנדסים צללו למאגר מים מתחת לכור הבוער כדי לפתוח שסתום ולנקז את המים. אם המים האלה היו רותחים בעקבות מסת הליבה המותכת שירדה, היה מתרחש פיצוץ קיטור משני שיכול היה להגדיל את האסון פי 10 ולפזר רדיואקטיביות על מחצית מאירופה. בניגוד לאגדה הרווחת — שלושתם שרדו את המשימה. אננקו ובז׳פאלוב חיים עד היום (2026).',
    desc_en: 'On 4-6 May three engineers dove into a water reservoir beneath the burning reactor to open a valve and drain the water. If this water boiled from the descending molten core mass, a secondary steam explosion would have multiplied the disaster tenfold and spread radioactivity over half of Europe. Contrary to popular legend — all three survived the mission. Ananenko and Bezpalov are alive today (2026).',
    risk: 'extreme', dose: 'שרדו' },
  { id: 'biorobot', icon: '🦾', he: 'ה"ביו-רובוטים" — מנקי הגג', en: 'Bio-Robots — Roof Cleaners', count: '~3,400',
    lead: '',
    desc_he: 'אחרי שרובוטים מתוצרת גרמניה ויפן נכשלו — האלקטרוניקה שלהם נשרפה מעוצמת הקרינה — נשלחו 3,400 חיילים סובייטיים מהמילואים, כל אחד למשך 40-90 שניות בלבד. כל חייל זרק 1-2 גושי גרפיט באת ורץ למטה. כינו אותם "ביו-רובוטים". ההגנה שלהם: סינר עופרת, קסדה, ומנ״פ.',
    desc_en: 'After German and Japanese robots failed — their electronics burned out by the radiation intensity — 3,400 Soviet reservist soldiers were sent, each for only 40-90 seconds. Each soldier shoveled 1-2 chunks of graphite then ran down. They were called "Bio-Robots." Their protection: lead apron, helmet, and SCBA.',
    risk: 'extreme', dose: '0.25 סיברט לסשן' },
  { id: 'sarc', icon: '🏗', he: 'בוני הסרקופג', en: 'Sarcophagus Builders', count: '~200,000',
    lead: '',
    desc_he: 'בוני הסרקופג הראשון ("אובייקט מקלט") שהוקם תוך 6 חודשים — ממאי עד נובמבר 1986. השתמשו בשלט-רחוק להזרמת בטון, אבל חלק מהעבודה נדרשה ידנית. בכמויות: 400,000 מ"ק בטון. 7,300 טון פלדה.',
    desc_en: 'Builders of the first sarcophagus, erected in 6 months — May to November 1986. They used remote control for concrete pumping, but some work required manual labor. Quantities: 400,000 m³ concrete. 7,300 tons of steel.',
    risk: 'high', dose: '~0.1-0.5 סיברט' },
  { id: 'evac', icon: '🚌', he: 'נהגי האוטובוסים', en: 'Bus Drivers', count: '~5,000',
    lead: '',
    desc_he: '1,200 אוטובוסים שפינו 49,000 תושבי פריפיאט תוך 3 שעות בלבד ב-27 באפריל. נהגי האוטובוסים שעברו דרך אזור הקרינה הגבוהה הבליעו מנות גבוהות. רבים מהאוטובוסים לא יכלו לחזור ונקברו בקבר רכבים מזוהמים.',
    desc_en: '1,200 buses that evacuated 49,000 Pripyat residents within just 3 hours on 27 April. Bus drivers passing through the high-radiation zone absorbed high doses. Many of the buses could not return and were buried in a contaminated vehicle graveyard.',
    risk: 'high', dose: '~0.05-0.2 סיברט' },
  { id: 'decon', icon: '🧹', he: 'צוותי הטיהור', en: 'Decontamination Teams', count: '~300,000',
    lead: '',
    desc_he: 'טיהור הקרקע, הבתים, הרכבים וכל פיסת אדמה באזור 30 ק״מ סביב הכור. השיטות: שטיפה במים מיוחדים, חיתוך וקבירה של 5 ס"מ אדמה עליונה, הריסת בתים שלמים. סך הכל 188 כפרים נקברו תחת אדמה ולא קיימים יותר.',
    desc_en: 'Decontamination of soil, houses, vehicles, and every patch of land in the 30 km zone around the reactor. Methods: washing with special chemicals, cutting and burying the top 5 cm of soil, demolishing entire houses. In total 188 villages were buried under earth and no longer exist.',
    risk: 'high', dose: '~0.05-0.3 סיברט' },
  { id: 'guard', icon: '🪖', he: 'משמרות ושמירה', en: 'Guards & Security', count: '~50,000',
    lead: '',
    desc_he: 'חיילים ששמרו על האזור הסגור, מנעו ביזה של בתים נטושים, וניהלו מחסומי כניסה. גם אחרי שהסיכון המיידי הסתיים, הם המשיכו לחיות באזור הקרינה במשך חודשים ואף שנים.',
    desc_en: 'Soldiers who guarded the exclusion zone, prevented looting of abandoned homes, and managed entry checkpoints. Even after the immediate danger ended, they continued living in the radiation area for months and even years.',
    risk: 'medium', dose: '~0.02-0.1 סיברט' },
  { id: 'medic', icon: '⚕️', he: 'הצוותים הרפואיים', en: 'Medical Teams', count: '~20,000',
    lead: 'ד״ר אנג׳לינה גוסקובה',
    desc_he: 'רופאים ואחיות שטיפלו בנפגעי קרינה חריפה בבית חולים מס׳ 6 במוסקבה ובאזור עצמו. ד״ר גוסקובה הייתה הראשונה בעולם שטיפלה במספר כה גדול של נפגעי קרינה חריפה. השתלות מח עצם נכשלו ברוב המקרים — הרקמה החדשה לא הצליחה לתפקד תחת רעלי הקרינה שהצטברו בגוף.',
    desc_en: 'Doctors and nurses who treated acute radiation casualties at Hospital No. 6 in Moscow and on-site. Dr. Guskova was the first in the world to treat such a large number of acute radiation casualties. Bone marrow transplants failed in most cases — the new tissue could not function under the radiation toxins accumulated in the body.',
    risk: 'medium', dose: 'מגע נמוך' },
];

// =================== CASUALTIES & STATS ===================
export const CASUALTIES = {
  immediate: [
    { n: '2', he: 'הרוגים מיידיים בפיצוץ', en: 'Immediate explosion deaths', detail_he: 'אחד נמחץ בהריסות (חודמצ׳וק), השני (שאשנוק) נכווה קשות', detail_en: 'One crushed in debris (Khodemchuk), one severely burned (Shashenok)' },
    { n: '134', he: 'אובחנו בתסמונת קרינה חריפה', en: 'Diagnosed with severe ARS', detail_he: 'תסמונת קרינה חריפה — מחלת קרינה הנגרמת מחשיפה למנה גבוהה של קרינה תוך זמן קצר. הליקווידטורים והכבאים הובאו לבית חולים מס׳ 6 במוסקבה.', detail_en: 'Acute Radiation Syndrome — illness from exposure to high radiation dose in short time. Liquidators and firefighters taken to Moscow Hospital No. 6.' },
    { n: '28', he: 'מתו תוך 3 חודשים', en: 'Died within 3 months', detail_he: 'רובם הכבאים הראשונים שעלו לגג', detail_en: 'Mostly first firefighters who climbed the roof' },
    { n: '~31', he: 'הרוגים מאומתים מהאסון', en: 'Confirmed deaths from disaster', detail_he: 'נתון רשמי של IAEA ו-UNSCEAR', detail_en: 'IAEA + UNSCEAR official figure' },
  ],
  longterm: [
    { n: '6,000+', he: 'מקרי סרטן בלוטת התריס בילדים', en: 'Childhood thyroid cancer cases', detail_he: 'בעיקר בבלארוס ואוקראינה. רובם נרפאו בניתוח וטיפול. כ-15 מתו עד 2005.', detail_en: 'Mainly in Belarus and Ukraine. Most were cured by surgery and treatment. About 15 died by 2005.' },
    { n: '~9,000', he: 'מקרי סרטן עודפים צפויים', en: 'Expected excess cancer cases', detail_he: 'הערכת UNSCEAR לטווח ארוך באזור המזוהם הקרוב', detail_en: 'UNSCEAR long-term estimate in immediate contaminated area' },
    { n: '16,000', he: 'מקרי סרטן עודפים באירופה', en: 'Excess cancer cases in Europe', detail_he: 'הערכה ל-50 שנה הקרובות (Cardis et al. 2006)', detail_en: 'Estimate over the next 50 years (Cardis et al. 2006)' },
    { n: '~10%', he: 'תמותה עודפת בקרב הליקווידטורים', en: 'Excess mortality among liquidators', detail_he: 'הערכת UNSCEAR אחרי 30 שנה', detail_en: 'UNSCEAR estimate after 30 years' },
  ],
  evac: [
    { n: '49,000', he: 'תושבי פריפיאט פונו', en: 'Pripyat residents evacuated', detail_he: '27/4/86, ב-1,200 אוטובוסים תוך 3 שעות', detail_en: '27/4/86, in 1,200 buses within 3 hours' },
    { n: '116,000', he: 'פונו מאזור 30 ק״מ ב-1986', en: 'Evacuated from 30km zone in 1986', detail_he: '88 כפרים פונו עד אוקטובר 1986', detail_en: '88 villages evacuated by October 1986' },
    { n: '~350,000', he: 'סך הפינויים בטווח הארוך', en: 'Total long-term resettlement', detail_he: 'מאוקראינה, בלארוס ורוסיה (UNSCEAR)', detail_en: 'From Ukraine, Belarus, Russia (UNSCEAR)' },
    { n: '188', he: 'כפרים נקברו תחת אדמה', en: 'Villages buried under earth', detail_he: 'שיטת טיהור: הריסה וכיסוי בעפר נקי', detail_en: 'Decontamination method: demolish and cover with clean soil' },
  ],
};

// =================== RADIATION DATA ===================
export const ISOTOPES = [
  { name: 'Iodine-131', symbol: 'I-131', half: '8 ימים',
    he: 'יוד-131', target_he: 'בלוטת התריס', target_en: 'Thyroid gland',
    danger_he: 'נשאף או נבלע במזון/חלב מזוהם. גורם סרטן בלוטת התריס בילדים. זה האיזוטופ שגרם לרוב המקרים בילדי בלארוס ואוקראינה.',
    danger_en: 'Inhaled or ingested via contaminated food/milk. Causes childhood thyroid cancer. This is the isotope responsible for most cases in Belarusian and Ukrainian children.',
    released: '~1,760 PBq', color: '#a855f7' },
  { name: 'Cesium-137', symbol: 'Cs-137', half: '30 שנה',
    he: 'צסיום-137', target_he: 'רקמות רכות בכל הגוף', target_en: 'Soft tissues throughout body',
    danger_he: 'גורם הזיהום ארוך-הטווח הראשי של אדמה ומזון. עד היום נמצא באזור הסגור ובמזון מקומי. מחקה אשלגן ולכן נספג היטב בגוף.',
    danger_en: 'Main long-term contamination of soil and food. Still present today in the exclusion zone and local food. Mimics potassium and is well absorbed by the body.',
    released: '~85 PBq', color: '#dc2626' },
  { name: 'Strontium-90', symbol: 'Sr-90', half: '29 שנה',
    he: 'סטרונציום-90', target_he: 'עצמות ושיניים', target_en: 'Bones and teeth',
    danger_he: 'מחקה סידן ולכן משתלב בעצמות ובשיניים. גורם לסרטן עצם וללוקמיה. נשאר בעצמות לכל החיים.',
    danger_en: 'Mimics calcium so embeds in bones and teeth. Causes bone cancer and leukemia. Remains in bones for life.',
    released: '~10 PBq', color: '#f59e0b' },
  { name: 'Plutonium-239', symbol: 'Pu-239', half: '24,110 שנה',
    he: 'פלוטוניום-239', target_he: 'ריאות, עצמות, כבד', target_en: 'Lungs, bones, liver',
    danger_he: 'רעיל מאוד אם נשאף כאבק. נשאר באזור הסגור למאות אלפי שנים. הוא הסיבה העיקרית שהאזור לא יוכל להיות מיושב במאות השנים הקרובות.',
    danger_en: 'Highly toxic if inhaled as dust. Remains in exclusion zone for hundreds of thousands of years. Main reason the area cannot be inhabited for centuries to come.',
    released: '~0.03 PBq', color: '#22c55e' },
  { name: 'Xenon-133', symbol: 'Xe-133', half: '5 ימים',
    he: 'קסנון-133', target_he: 'גז אצילי — לא מתקבע בגוף', target_en: 'Noble gas — does not bind in body',
    danger_he: 'התפזר באטמוספירה. דעך תוך שבועות. נמדד לראשונה בשבדיה ב-28 באפריל 1986 וגרם לחשיפת האסון לעולם.',
    danger_en: 'Dispersed in atmosphere. Decayed within weeks. First measured in Sweden on 28 April 1986 and caused the disaster\'s exposure to the world.',
    released: '~6,500 PBq', color: '#06b6d4' },
];

export const DOSE_SCALE = [
  { mSv: 0.01, label_he: 'צילום שיניים', label_en: 'Dental X-ray', risk: 'safe' },
  { mSv: 0.1, label_he: 'צילום חזה', label_en: 'Chest X-ray', risk: 'safe' },
  { mSv: 2.4, label_he: 'קרינת רקע שנתית טבעית', label_en: 'Annual natural background radiation', risk: 'safe' },
  { mSv: 10, label_he: 'בדיקת CT בטן', label_en: 'Abdominal CT scan', risk: 'low' },
  { mSv: 50, label_he: 'גבול שנתי לעובדי קרינה', label_en: 'Annual occupational limit', risk: 'low' },
  { mSv: 100, label_he: 'סף עליה ניכרת בסיכון לסרטן', label_en: 'Threshold for cancer risk increase', risk: 'medium' },
  { mSv: 250, label_he: 'מנה ממוצעת לליקווידטור', label_en: 'Average liquidator dose', risk: 'medium' },
  { mSv: 1000, label_he: 'תסמונת קרינה קלה (בחילות)', label_en: 'Mild ARS (nausea)', risk: 'high' },
  { mSv: 4000, label_he: 'מוות ב-50% מהמקרים תוך 30 ימים', label_en: 'LD50 — 50% death within 30 days', risk: 'extreme' },
  { mSv: 8000, label_he: 'מוות ודאי תוך 3 שבועות', label_en: 'LD100 — certain death within 3 weeks', risk: 'extreme' },
  { mSv: 16000, label_he: 'הכבאים הראשונים בצ׳רנוביל', label_en: 'Chernobyl first firefighters', risk: 'extreme' },
  { mSv: 300000, label_he: 'מעל הליבה החשופה', label_en: 'Above exposed core', risk: 'extreme' },
];

// =================== GLOSSARY ===================
export const TERMS = [
  // Physics
  { cat: 'phys', he: 'ביקוע גרעיני', en: 'Nuclear Fission',
    def_he: 'התהליך שבו גרעין כבד (כמו אורניום-235) מתפצל לשני גרעינים קלים יותר, תוך שחרור אנרגיה רבה ופליטת ניוטרונים נוספים. זה התהליך הבסיסי שבכור גרעיני ייצור חשמל.',
    def_en: 'Process in which a heavy nucleus (like U-235) splits into two lighter nuclei, releasing large amounts of energy and emitting additional neutrons. The fundamental process by which a nuclear reactor produces electricity.' },
  { cat: 'phys', he: 'תגובת שרשרת', en: 'Chain Reaction',
    def_he: 'תהליך שבו ניוטרונים שמשתחררים מביקוע אחד גורמים לביקועים נוספים, וכך הלאה. בכור מבוקר, מספר הניוטרונים נשמר קבוע — תגובה יציבה. בפיצוץ צ׳רנוביל התגובה הפכה ללא מבוקרת.',
    def_en: 'Process where neutrons released from one fission cause additional fissions, and so on. In a controlled reactor, neutron count remains constant — stable reaction. In the Chernobyl explosion the reaction became uncontrolled.' },
  { cat: 'phys', he: 'מקדם החללות', en: 'Void Coefficient',
    def_he: 'תכונה פיזיקלית של הכור שקובעת מה קורה כשמים מתאדים לקיטור. ב-RBMK חיובי וגבוה (+4.7β) — בועות → יותר תגובה → יותר חום → יותר בועות. ברוב הכורים בעולם שלילי — מנגנון בטיחות מובנה. זה היה הפגם הקטלני ביותר ב-RBMK.',
    def_en: 'Physical property determining what happens when water vaporizes to steam. In RBMK positive and high (+4.7β) — voids → more reaction → more heat → more voids. In most reactors negative — built-in safety. This was RBMK\'s most lethal flaw.' },
  { cat: 'phys', he: 'קריטיות פרומפטית', en: 'Prompt Criticality',
    def_he: 'מצב מסוכן שבו תגובת השרשרת מתחזקת באמצעות ניוטרונים מהירים בלבד, ללא יכולת בקרה. העוצמה יכולה לזנק תוך מילישניות. זה מה שקרה ב-01:23:45 ב-26/4/86.',
    def_en: 'Dangerous state where the chain reaction strengthens via prompt neutrons alone, without control capability. Power can spike within milliseconds. This is what happened at 01:23:45 on 26/4/86.' },
  { cat: 'phys', he: 'מאט (Moderator)', en: 'Moderator',
    def_he: 'חומר שמאט ניוטרונים מהירים, כדי שיוכלו לגרום לביקוע. ב-RBMK: גרפיט (1,700 טון). בכורים מערביים: מים בלחץ. הבחירה במאט שונה ממים גרמה לפגם הבטיחות הקריטי ב-RBMK.',
    def_en: 'Material slowing fast neutrons so they can cause fission. In RBMK: graphite (1,700 tons). In Western reactors: pressurized water. The choice of non-water moderator caused the critical safety flaw in RBMK.' },
  { cat: 'phys', he: 'אורניום מועשר', en: 'Enriched Uranium',
    def_he: 'אורניום שבו הוגדל ריכוז האיזוטופ U-235 (זה שניתן לבקיעה) מעל הריכוז הטבעי (0.7%). דלק RBMK הכיל 2.0% U-235. דלק לפצצה גרעינית דורש 90%+.',
    def_en: 'Uranium with elevated U-235 isotope (the fissile one) above natural concentration (0.7%). RBMK fuel contained 2.0% U-235. Nuclear weapon-grade requires 90%+.' },
  { cat: 'phys', he: 'הרעלת קסנון', en: 'Xenon Poisoning',
    def_he: 'הצטברות גז קסנון-135 בכור — בולע ניוטרונים בכמות גדולה ומדכא את התגובה. בכור פעיל הוא נשרף כל הזמן. בעוצמה נמוכה הוא מצטבר. הצעד הבטוח: לכבות 2-3 ימים. ב-26/4 הצוות עשה ההפך.',
    def_en: 'Buildup of Xenon-135 gas in reactor — absorbs large amounts of neutrons and suppresses reaction. In active reactor it constantly burns up. At low power it accumulates. Safe step: shut down 2-3 days. On 26/4 the crew did the opposite.' },
  { cat: 'phys', he: 'תגובתיות', en: 'Reactivity',
    def_he: 'מידת הסטייה של הכור ממצב יציב (קריטיות). תגובתיות חיובית = העוצמה עולה. תגובתיות שלילית = העוצמה יורדת. נמדדת ביחידות β.',
    def_en: 'Reactor deviation from stable critical state. Positive reactivity = power rising. Negative = power falling. Measured in β units.' },

  // Reactor systems
  { cat: 'reactor', he: 'RBMK', en: 'RBMK Reactor',
    def_he: 'כור גרעיני סובייטי — "כור-תעלות בעל הספק רב" (תרגום מרוסית). מאט גרפיט, קירור מים, מבנה תעלות. לא היה לו מבנה הכלה (containment) חיצוני כמו בכורים מערביים. אחרי האסון כל ה-RBMKים שודרגו.',
    def_en: 'Soviet nuclear reactor — "High-Power Channel-Type Reactor" (translated from Russian). Graphite moderator, water cooling, channel structure. Lacked outer containment unlike Western reactors. After the disaster all RBMKs were upgraded.' },
  { cat: 'reactor', he: 'מוטות בקרה', en: 'Control Rods',
    def_he: 'מוטות עשויים מבורון או קדמיום שסופחים ניוטרונים. מחדירים אותם לליבה כדי להאט או לעצור את התגובה. ב-RBMK: 211 מוטות עם פגם הקצה הגרפיטי שהפך אותם מבולמי בטיחות לקטליזטור הפיצוץ.',
    def_en: 'Rods of boron or cadmium that absorb neutrons. Inserted into core to slow or stop reaction. In RBMK: 211 rods with the graphite tip flaw that turned them from safety brakes into the explosion trigger.' },
  { cat: 'reactor', he: 'AZ-5 (כפתור עצירת חירום)', en: 'AZ-5 (Emergency Stop)',
    def_he: 'כפתור עצירת החירום של הכור. בכור תקין הוא היה אמור לעצור את התגובה תוך שניות. בצ׳רנוביל ב-26/4/86 בשעה 01:23:40 הלחיצה עליו גרמה לפיצוץ במקום לעצירה — בגלל פגם תכן של מוטות הבקרה.',
    def_en: 'Reactor emergency stop button. In a properly designed reactor it should stop the reaction within seconds. At Chernobyl on 26/4/86 at 01:23:40 pressing it caused the explosion instead of stopping — due to control rod design flaw.' },
  { cat: 'reactor', he: 'מערכת קירור החירום (ECCS)', en: 'Emergency Core Cooling System',
    def_he: 'מערכת בטיחות שמציפה את הכור במים אם הקירור הראשי נכשל. בצ׳רנוביל ב-25/4 בשעה 14:00 — שעות לפני האסון — היא נותקה ידנית כדי לא להפריע לניסוי. הפרת רישיון תפעולי בולטת.',
    def_en: 'Safety system that floods reactor with water if primary cooling fails. At Chernobyl on 25/4 at 14:00 — hours before the disaster — it was manually disabled to not interfere with the test. Major operating license violation.' },
  { cat: 'reactor', he: 'רזרבת מוטות בקרה (ORM)', en: 'Operational Reactivity Margin',
    def_he: 'מספר מוטות הבקרה שצריכים להישאר בליבה כל הזמן כרזרבה בטיחותית. המינימום שמותר על פי תקנון: 30 מוטות. בעת הפיצוץ ב-26/4 היו רק 8.',
    def_en: 'Number of control rods that must always remain in the core as safety reserve. Regulatory minimum: 30 rods. At time of explosion on 26/4 only 8 remained.' },
  { cat: 'reactor', he: 'תופי הפרדת קיטור', en: 'Steam Separator Drums',
    def_he: '4 גלילים אופקיים גדולים (30 מ׳) שמפרידים את תערובת המים-קיטור היוצאת מהליבה — קיטור לטורבינה, מים בחזרה לכור.',
    def_en: '4 large horizontal cylinders (30m) that separate the water-steam mixture exiting the core — steam to turbine, water back to reactor.' },
  { cat: 'reactor', he: 'מכל הלחץ של הכור', en: 'Pressure Vessel',
    def_he: 'מכל פלדה-בטון העוטף את הכור. ב-RBMK: 26 מ׳ × 21.6 מ׳, ללא מבנה הכלה (containment) חיצוני. בכורים מערביים יש כיפת בטון עבה נוספת מסביב.',
    def_en: 'Steel-concrete vessel housing reactor. In RBMK: 26m × 21.6m, no outer containment. Western reactors have additional thick concrete dome around it.' },
  { cat: 'reactor', he: 'תעלת לחץ', en: 'Pressure Tube',
    def_he: 'צינור מסגסוגת זירקאלוי שמכיל ערוץ דלק עם מים זורמים. ב-RBMK יש 1,661 מהם — אחד לכל מוט דלק.',
    def_en: 'Zircaloy alloy tube containing fuel channel with flowing water. RBMK has 1,661 — one per fuel rod.' },
  { cat: 'reactor', he: 'לוח המגן הביולוגי "סכמה E"', en: 'Schema E Bio-Shield',
    def_he: 'לוח פלדה-בטון של 2,000 טון שאמור לכסות את החלק העליון של הכור ולחסום קרינה. בפיצוץ נזרק לאוויר ונחת בזווית של 15 מעלות מעל הליבה החשופה.',
    def_en: 'Steel-concrete plate of 2,000 tons meant to cap the reactor top and block radiation. In the explosion was thrown to the air and landed at 15-degree angle over the exposed core.' },
  { cat: 'reactor', he: 'משאבת קירור ראשית', en: 'Main Circulation Pump',
    def_he: 'משאבה צנטריפוגלית שדוחפת מי קירור דרך הכור. ב-RBMK יש 8 (6 פעילות + 2 רזרבה).',
    def_en: 'Centrifugal pump pushing coolant through reactor. RBMK has 8 (6 active + 2 reserve).' },
  { cat: 'reactor', he: 'גנרטורי דיזל לחירום', en: 'Emergency Diesel Generators',
    def_he: '3 גנרטורים שאמורים לספק חשמל למשאבות הקירור בעת תקלה. זמן ההתנעה שלהם — בערך דקה — היא הסיבה לכל ניסוי הטורבינה ב-26/4.',
    def_en: '3 generators meant to supply power to cooling pumps during failure. Their startup time — about a minute — is the very reason for the entire turbine test on 26/4.' },
  { cat: 'reactor', he: 'כור PWR מערבי', en: 'Western PWR Reactor',
    def_he: 'כור מים בלחץ (Pressurized Water Reactor) — סוג מערבי הנפוץ ביותר בעולם. שונה מ-RBMK בכך שהמים משמשים גם כמאט וגם לקירור — מנגנון בטיחות מובנה. אם המים מתאדים, התגובה דועכת.',
    def_en: 'Pressurized Water Reactor — most common Western type globally. Differs from RBMK in that water serves as both moderator and coolant — built-in safety mechanism. If water vaporizes, reaction subsides.' },
  { cat: 'reactor', he: 'כור BWR מערבי', en: 'Western BWR Reactor',
    def_he: 'כור מים רותחים (Boiling Water Reactor) — סוג מערבי. דומה ל-PWR אבל הקיטור נוצר ישירות בליבה. גם לו יש מנגנון בטיחות מובנה דרך מי-מאט.',
    def_en: 'Boiling Water Reactor — Western type. Similar to PWR but steam created directly in core. Also has built-in safety mechanism via water-moderator.' },

  // Radiation
  { cat: 'rad', he: 'תסמונת קרינה חריפה', en: 'Acute Radiation Syndrome (ARS)',
    def_he: 'מחלה הנגרמת מחשיפה למנת קרינה גבוהה (מעל 1 גריי) בזמן קצר. תסמינים: בחילות, הקאות, פגיעה במח עצם, פגיעה במערכת העיכול, ובמקרים חמורים — מוות תוך שבועות. 28 כבאים בצ׳רנוביל מתו מ-ARS.',
    def_en: 'Disease from high radiation exposure (over 1 Gy) in short time. Symptoms: nausea, vomiting, bone marrow damage, GI damage, and in severe cases — death within weeks. 28 firefighters at Chernobyl died from ARS.' },
  { cat: 'rad', he: 'מנת קרינה', en: 'Radiation Dose',
    def_he: 'כמות הקרינה שנספגה ברקמה. נמדדת ב-Gray (גריי) לאנרגיה הנספגת, או Sievert (סיברט) לנזק הביולוגי המשוקלל.',
    def_en: 'Amount of radiation absorbed by tissue. Measured in Gray (Gy) for absorbed energy, or Sievert (Sv) for biologically-weighted damage.' },
  { cat: 'rad', he: 'קרני גמא', en: 'Gamma Rays',
    def_he: 'קרינה אלקטרומגנטית בעלת אנרגיה גבוהה ויכולת חדירה גדולה. כדי לעצור אותן צריך עופרת או בטון בעובי משמעותי.',
    def_en: 'High-energy electromagnetic radiation with great penetration. To stop them requires significant thickness of lead or concrete.' },
  { cat: 'rad', he: 'קרני בטא', en: 'Beta Particles',
    def_he: 'אלקטרונים מהירים. נעצרים על ידי לוח אלומיניום או בגדים עבים. הסכנה העיקרית: במגע עורי או אם נבלעים פנימה.',
    def_en: 'Fast electrons. Stopped by aluminum sheet or thick clothing. Main danger: skin contact or ingestion.' },
  { cat: 'rad', he: 'יוד-131', en: 'Iodine-131',
    def_he: 'איזוטופ רדיואקטיבי בעל זמן מחצית-חיים של 8 ימים. נספג על ידי בלוטת התריס וגורם סרטן בלוטת התריס בילדים. זה האיזוטופ שגרם לרוב המקרים בילדי בלארוס ואוקראינה.',
    def_en: 'Radioactive isotope with 8-day half-life. Absorbed by thyroid gland, causing childhood thyroid cancer. This is the isotope responsible for most cases in Belarusian and Ukrainian children.' },
  { cat: 'rad', he: 'צסיום-137', en: 'Cesium-137',
    def_he: 'איזוטופ רדיואקטיבי בעל זמן מחצית-חיים של 30 שנה. אחראי לזיהום ארוך-טווח של אדמה ומזון. עדיין נמדד באזור הסגור עד היום.',
    def_en: 'Radioactive isotope with 30-year half-life. Responsible for long-term soil and food contamination. Still measured in the exclusion zone today.' },
  { cat: 'rad', he: 'סטרונציום-90', en: 'Strontium-90',
    def_he: 'מחקה סידן ולכן משתלב בעצמות ובשיניים. מחצית-חיים: 29 שנה. גורם סרטן עצם ולוקמיה. נשאר בעצמות לכל החיים.',
    def_en: 'Mimics calcium and embeds in bones and teeth. Half-life: 29 years. Causes bone cancer and leukemia. Remains in bones for life.' },
  { cat: 'rad', he: 'פלוטוניום-239', en: 'Plutonium-239',
    def_he: 'איזוטופ של פלוטוניום בעל זמן מחצית-חיים של 24,000 שנה. רעיל מאוד אם נשאף או נבלע. הוא הסיבה שאזור צ׳רנוביל לא יוכל להיות מיושב במאות השנים הקרובות.',
    def_en: 'Plutonium isotope with 24,000-year half-life. Highly toxic if inhaled or ingested. The reason the Chernobyl area cannot be inhabited for centuries to come.' },
  { cat: 'rad', he: 'מחצית-חיים', en: 'Half-Life',
    def_he: 'הזמן הנדרש לחצי מאיזוטופ רדיואקטיבי להתפרק. דוגמאות: יוד-131 (8 ימים), צסיום-137 (30 שנה), פלוטוניום-239 (24,000 שנה).',
    def_en: 'Time required for half a radioactive isotope to decay. Examples: I-131 (8 days), Cs-137 (30 years), Pu-239 (24,000 years).' },
  { cat: 'rad', he: 'פטה-בקרל (PBq)', en: 'Petabecquerel (PBq)',
    def_he: 'יחידת מדידה של פעילות רדיואקטיבית. 1 פטה-בקרל = פירוקים בשנייה במספר עצום (10 בחזקת 15). מצ׳רנוביל שוחרר 5,300 פטה-בקרל של חומר רדיואקטיבי — בערך 400 פעמים פצצת הירושימה.',
    def_en: 'Unit of radioactive activity. 1 PBq = 10¹⁵ decays per second. Chernobyl released 5,300 PBq of radioactive material — about 400 times the Hiroshima bomb.' },
  { cat: 'rad', he: 'גריי (Gy)', en: 'Gray (Gy)',
    def_he: 'יחידה לאנרגיית קרינה שנספגה ברקמה. 1 גריי = 1 ג׳אול לק"ג רקמה. חשיפה של 4-5 גריי לכל הגוף בו-זמנית גורמת למוות ב-50% מהמקרים תוך 30 ימים.',
    def_en: 'Unit of radiation energy absorbed by tissue. 1 Gy = 1 Joule/kg of tissue. Whole-body exposure of 4-5 Gy causes death in 50% of cases within 30 days.' },
  { cat: 'rad', he: 'סיברט (Sv)', en: 'Sievert (Sv)',
    def_he: 'יחידת מנת קרינה משוקללת ביולוגית — לוקחת בחשבון את סוג הקרינה ומידת הסכנה שלה. עבור גמא: 1 סיברט = 1 גריי. עבור אלפא (מסוכנת יותר): 1 סיברט = 0.05 גריי בלבד.',
    def_en: 'Biologically-weighted dose unit — accounts for radiation type and danger level. For gamma: 1 Sv = 1 Gy. For alpha (more dangerous): 1 Sv = 0.05 Gy only.' },

  // The Disaster
  { cat: 'dis', he: 'ליקווידטורים', en: 'Liquidators',
    def_he: 'הכינוי לכ-600,000 חיילים, פועלים, מומחים ורופאים שעבדו על ניקוי האסון בין השנים 1986-1990. רובם המכריע גוייסו ללא הכשרה ייעודית. רבים שילמו בבריאותם.',
    def_en: 'Term for ~600,000 soldiers, workers, specialists, and doctors who worked on disaster cleanup between 1986-1990. Most were drafted without specialized training. Many paid with their health.' },
  { cat: 'dis', he: 'האזור הסגור', en: 'Exclusion Zone',
    def_he: 'אזור סביב הכור שאסור להיכנס אליו: 30 ק״מ ב-1986, ולאחר מכן הורחב ל-2,600 קמ״ר. תושביו פונו בכפייה ואסורה כניסה ללא היתר. עד היום פעיל. המונח הרשמי בעברית הוא "אזור הדרה" — מלשון להדיר/להרחיק.',
    def_en: '30 km zone around reactor (later 2,600 km²) with forced evacuation and entry prohibited.' },
  { cat: 'dis', he: 'הסרקופג', en: 'Sarcophagus',
    def_he: 'מבנה הבטון "אובייקט מקלט" שהוקם על הריסות יחידה 4 ב-1986 כדי לעצור פליטת קרינה. תוכנן לעמידות 30 שנה. הוחלף ב-2016 בסגירה החדשה.',
    def_en: 'The "Object Shelter" concrete structure built over Unit 4 ruins in 1986 to stop radiation emission. Designed for 30 years. Replaced in 2016 by New Safe Confinement.' },
  { cat: 'dis', he: 'הסגירה החדשה', en: 'New Safe Confinement',
    def_he: 'מבנה מתכת ענקי (108 מ׳ גובה, 36,000 טון, הגדול בעולם מסוגו) שהוסט ב-29/11/2016 על הסרקופג הישן. תוכנן לעמידות של 100 שנה. עתיד לאפשר פירוק מבוקר של הריסות הכור.',
    def_en: 'Massive metal structure (108m tall, 36,000 tons, world\'s largest of its kind) slid on 29/11/2016 over the old sarcophagus. Designed for 100-year lifespan. Will eventually enable controlled dismantling of reactor ruins.' },
  { cat: 'dis', he: 'פינוי פריפיאט', en: 'Pripyat Evacuation',
    def_he: 'פינוי 49,000 תושבי פריפיאט תוך 3 שעות בלבד ב-27/4/1986, ב-1,200 אוטובוסים. ההודעה לתושבים: "חזרו תוך 3 ימים". איש לא חזר לעולם — העיר נטושה עד היום.',
    def_en: 'Evacuation of 49,000 Pripyat residents within just 3 hours on 27/4/1986, in 1,200 buses. The announcement to residents: "Return in 3 days". Nobody ever returned — the city remains abandoned today.' },
  { cat: 'dis', he: '"רגל הפיל"', en: '"Elephant\'s Foot"',
    def_he: 'מסת לבה רדיואקטיבית עצומה (Corium — תערובת של דלק מותך, פלדה, גרפיט ובטון) שזרמה ממה שנותר מהליבה אל מרתפי הכור. ב-1986 הקרינה שלה הגיעה ל-8,000 רנטגן לשעה — קטלנית בתוך דקות.',
    def_en: 'Massive mass of radioactive lava (Corium — mixture of melted fuel, steel, graphite, and concrete) that flowed from core remnants into reactor basements. In 1986 its radiation reached 8,000 R/hr — fatal within minutes.' },
  { cat: 'dis', he: 'Corium (לבה גרעינית)', en: 'Corium',
    def_he: 'תערובת מותכת של דלק גרעיני, פלדה, גרפיט ובטון, שנוצרה בעת הריסת הליבה. בעברית מקצועית מכונה "חרבית" — מהמילה "חרבה" (יציקה).',
    def_en: 'Molten mixture of nuclear fuel, steel, graphite, and concrete formed during core meltdown.' },

  // Firefighting & HazMat
  { cat: 'fire', he: 'מנ״פ', en: 'Self-Contained Breathing Apparatus (SCBA)',
    def_he: 'מערכת נשימה עצמית — מכל אוויר נישא על הגב, המספק אוויר נקי לכבאי. ראשי תיבות: מערכת נשימה פתוחה. בצ׳רנוביל ב-1986 לא היה זמין לכל הצוותים שהגיעו.',
    def_en: 'Back-mounted air tank supplying clean air to firefighters. At Chernobyl 1986 was not available to all responding crews.' },
  { cat: 'fire', he: 'מב״ר', en: 'Initial Isolation Distance',
    def_he: 'מרחק בידוד ראשוני — המרחק המינימלי שצריך לפנות סביב חומר מסוכן. בקרינה גרעינית: 100 מטר במבנה סגור / 200 מטר באוויר פתוח (לפי ה-ERG 2024).',
    def_en: 'Minimum distance to evacuate around hazardous material. For nuclear radiation: 100m enclosed / 200m open air (per ERG 2024).' },
  { cat: 'fire', he: 'ERG — מדריך התגובה לחירום', en: 'ERG — Emergency Response Guide',
    def_he: 'מדריך בינלאומי לטיפול בחומרים מסוכנים, מהדורת 2024. כולל כללי טיפול בחומרים רדיואקטיביים, מרחקי בידוד, וציוד נדרש.',
    def_en: 'International hazmat response guide, 2024 edition. Includes radioactive material protocols, isolation distances, and required equipment.' },
  { cat: 'fire', he: 'ספיחה', en: 'Adsorption',
    def_he: 'הצמדה של מולקולות חומר לפני שטח של חומר אחר — כמו מים שנדבקים לזכוכית. שונה מ"בליעה" (Absorption) שהיא חדירה לתוך החומר. רלוונטי לטיהור קרינה: שילוב חלקיקים רדיואקטיביים בחומר ספוג.',
    def_en: 'Adhesion of substance molecules to another\'s surface — like water sticking to glass. Different from "absorption" which is penetration into the material. Relevant to radiation decontamination.' },
  { cat: 'fire', he: 'טיהור', en: 'Decontamination',
    def_he: 'הסרת חומר רדיואקטיבי מציוד, מבנים, או אנשים. השיטות בצ׳רנוביל: שטיפה במים מיוחדים עם דטרגנטים, חיתוך וקבירה של 5 ס"מ אדמה עליונה, הריסת בתים שלמים.',
    def_en: 'Removal of radioactive material from equipment, buildings, or people. Methods at Chernobyl: washing with special water and detergents, cutting and burying top 5cm of soil, demolishing entire houses.' },

  // Organizations
  { cat: 'org', he: 'IAEA — סוכנות האנרגיה האטומית', en: 'IAEA — International Atomic Energy Agency',
    def_he: 'הסוכנות הבינלאומית לאנרגיה אטומית. פרסמה את דוח INSAG-7 (1992) — הניתוח הסמכותי והרשמי של אסון צ׳רנוביל.',
    def_en: 'International Atomic Energy Agency. Published INSAG-7 (1992) — authoritative official analysis of Chernobyl disaster.' },
  { cat: 'org', he: 'INSAG-7', en: 'INSAG-7 Report',
    def_he: 'דוח קבוצת הייעוץ הבינלאומית לבטיחות גרעינית, 1992. הניתוח הרשמי של אסון צ׳רנוביל — קובע אחריות הן בפגמי תכן של RBMK והן בטעויות מפעילים.',
    def_en: 'International Nuclear Safety Advisory Group report, 1992. Official Chernobyl analysis — assigns responsibility both to RBMK design flaws and operator errors.' },
  { cat: 'org', he: 'UNSCEAR', en: 'UNSCEAR',
    def_he: 'הוועדה המדעית של האו״ם להשפעות הקרינה האטומית. דוח 2008 שלה הוא הבסיס לסיכומי בריאות מאסון צ׳רנוביל.',
    def_en: 'UN Scientific Committee on the Effects of Atomic Radiation. Its 2008 report is foundation for Chernobyl health summaries.' },
  { cat: 'org', he: 'WHO — ארגון הבריאות העולמי', en: 'WHO — World Health Organization',
    def_he: 'דוח 2006 של WHO ("השפעות בריאות של תאונת צ׳רנוביל") הוא המקור המרכזי להשלכות הבריאותיות לטווח ארוך.',
    def_en: 'WHO 2006 report ("Health Effects of the Chernobyl Accident") is primary source for long-term health consequences.' },
];

export const TERM_CAT: Record<string, { c: string; he: string; en: string }> = {
  phys: { c: '#a855f7', he: 'פיזיקה גרעינית', en: 'Nuclear Physics' },
  reactor: { c: '#c8a44e', he: 'מערכות הכור', en: 'Reactor Systems' },
  rad: { c: '#22c55e', he: 'קרינה ובריאות', en: 'Radiation & Health' },
  dis: { c: '#dc2626', he: 'האסון', en: 'The Disaster' },
  fire: { c: '#f59e0b', he: 'כבאות וחומ״ס', en: 'Firefighting & HazMat' },
  org: { c: '#06b6d4', he: 'ארגונים', en: 'Organizations' },
};

// =================== SOURCES ===================
export const SOURCES = [
  { cat: 'iaea', icon: '📋', title: 'IAEA INSAG-7 (1992)', subtitle: 'הניתוח הסמכותי הרשמי של האסון',
    desc_he: 'הניתוח הסמכותי הרשמי של אסון צ׳רנוביל. מאשים גם פגמי תכן של RBMK וגם טעויות מפעילים. מסמך הבסיס לכל ניתוח מקצועי.',
    desc_en: 'Authoritative official analysis. Blames both RBMK design flaws and operator errors. Foundation document.',
    url: 'https://www-pub.iaea.org/MTCD/publications/PDF/Pub913e_web.pdf', year: 1992 },
  { cat: 'iaea', icon: '📋', title: 'IAEA INSAG-1 (1986)', subtitle: 'הדוח הראשון אחרי האסון',
    desc_he: 'הדוח הראשון אחרי האסון. הוצא ב-1986 עוד תחת ההגדרה הסובייטית — שהאשים בעיקר את המפעילים. תוקן בהמשך ב-INSAG-7.',
    desc_en: 'First post-accident report. Published 1986 under Soviet narrative — primarily blamed operators. Later corrected by INSAG-7.',
    url: 'https://www-pub.iaea.org/MTCD/publications/PDF/Pub913e_web.pdf', year: 1986 },
  { cat: 'unscear', icon: '🔬', title: 'UNSCEAR 2008 — נספח D', subtitle: 'השפעות בריאותיות מצ׳רנוביל',
    desc_he: 'דוח הוועדה המדעית של האו״ם. הסיכום המקיף של ההשפעות הבריאותיות לטווח ארוך. 6,000+ מקרי סרטן בלוטת התריס בילדים.',
    desc_en: 'UN Scientific Committee report. Comprehensive summary of long-term health effects.',
    url: 'https://www.unscear.org/docs/reports/2008/11-80076_Report_2008_Annex_D.pdf', year: 2008 },
  { cat: 'who', icon: '🏥', title: 'WHO 2006', subtitle: 'השפעות בריאותיות של תאונת צ׳רנוביל',
    desc_he: 'דוח ארגון הבריאות העולמי, שנה אחרי 20 לאסון. מקור עיקרי להשלכות בריאותיות לטווח ארוך.',
    desc_en: 'World Health Organization report. 20 years after disaster. Primary source for long-term health.',
    url: 'https://www.who.int/publications/i/item/9241594179', year: 2006 },
  { cat: 'nrc', icon: '⚛', title: 'US NRC NUREG-1250', subtitle: 'דוח טכני אמריקאי',
    desc_he: 'דוח ועדת הרגולציה הגרעינית האמריקאית. ניתוח טכני מפורט מנקודת מבט מערבית.',
    desc_en: 'US Nuclear Regulatory Commission report. Detailed technical analysis from Western perspective.',
    url: 'https://www.nrc.gov/docs/ML0716/ML071690245.pdf', year: 1987 },
  { cat: 'book', icon: '📚', title: 'אדם היגינבותם — חצות בצ׳רנוביל', subtitle: 'הסיפור שלא סופר',
    desc_he: 'הספר העיתונאי הטוב ביותר על האסון. מחקר של 5 שנים, ראיונות עם ניצולים, מסמכים סובייטיים. כיסוי דקה-אחר-דקה.',
    desc_en: 'Best journalistic book on disaster. 5 years research, survivor interviews, Soviet documents. Minute-by-minute.',
    url: 'https://www.simonandschuster.com/books/Midnight-in-Chernobyl/Adam-Higginbotham/9781501134630', year: 2019 },
  { cat: 'book', icon: '📚', title: 'סרהי פלוחי — צ׳רנוביל', subtitle: 'היסטוריה של טרגדיה (פוליצר 2018)',
    desc_he: 'ספר מאת היסטוריון אוקראיני מהרווארד. זוכה פרס פוליצר 2018. ניתוח רחב יותר של ההקשר הסובייטי.',
    desc_en: 'Book by Ukrainian historian at Harvard. Pulitzer Prize 2018. Broader Soviet context analysis.',
    url: 'https://www.basicbooks.com/titles/serhii-plokhy/chernobyl/9781541617094/', year: 2018 },
  { cat: 'book', icon: '📚', title: 'סבטלנה אלכסייביץ׳ — קולות מצ׳רנוביל', subtitle: 'נובל לספרות 2015',
    desc_he: 'ספר עדויות אישיות של ניצולים, ליקווידטורים, ובני משפחותיהם. הסופרת זכתה בנובל לספרות 2015 בהשראה ממנו.',
    desc_en: 'Personal testimonies from survivors, liquidators, and family members. Author won Nobel 2015.',
    url: 'https://www.penguinrandomhouse.com/books/93009/voices-from-chernobyl-by-svetlana-alexievich/', year: 1997 },
  { cat: 'doc', icon: '🎬', title: 'HBO — צ׳רנוביל (2019)', subtitle: 'סדרת מיני בת 5 פרקים',
    desc_he: 'סדרת המיני המוערכת מאוד. ברובה מדויקת מבחינה היסטורית. הפיקה מודעות ציבורית עצומה.',
    desc_en: 'Highly acclaimed miniseries. Mostly historically accurate. Generated huge public awareness.',
    url: 'https://www.hbo.com/chernobyl', year: 2019 },
  { cat: 'doc', icon: '🎬', title: 'BBC — צ׳רנוביל: הסיפור האמיתי', subtitle: 'דוקומנטרי',
    desc_he: 'דוקומנטרי BBC עם ראיונות עד והצגת מסמכים. השלמה טובה לסדרת HBO.',
    desc_en: 'BBC documentary with eyewitness interviews and document presentation.',
    url: 'https://www.bbc.co.uk/programmes/p07cyh3y', year: 2019 },
  { cat: 'web', icon: '🌐', title: 'Chernobyl Gallery', subtitle: 'ארכיון תמונות',
    desc_he: 'ארכיון תמונות מקיף של האסון, פריפיאט, האזור הסגור.',
    desc_en: 'Comprehensive photo archive of disaster, Pripyat, exclusion zone.',
    url: 'https://chernobylgallery.com/', year: null },
  { cat: 'web', icon: '🌐', title: 'World Nuclear Association', subtitle: 'סיכום טכני של האסון',
    desc_he: 'סיכום טכני מקיף של האסון על ידי האגודה הגרעינית העולמית.',
    desc_en: 'Comprehensive technical summary by World Nuclear Association.',
    url: 'https://world-nuclear.org/information-library/safety-and-security/safety-of-plants/chernobyl-accident.aspx', year: null },
  { cat: 'web', icon: '🌐', title: 'אתר רשמי של האזור הסגור', subtitle: 'מידע ממשלתי אוקראיני',
    desc_he: 'אתר רשמי של האזור הסגור האוקראיני. מידע נוכחי על מצב הסגירה החדשה, פעילות מחקר, וטיולים.',
    desc_en: 'Official Ukrainian Exclusion Zone site. Current info on NSC, research, and tours.',
    url: 'https://www.chernobyl-tour.com/', year: null },
  { cat: 'sci', icon: '🇮🇱', title: 'מכון דוידסון — אורי טייכמן', subtitle: 'התאונה הגרעינית הקשה ביותר',
    desc_he: 'הסבר מקצועי בעברית של הזרוע החינוכית של מכון ויצמן. כולל: 3 ניסויי טורבינה קודמים שנכשלו, 3 גנרטורי דיזל, מנגנון בטיחות מובנה של כורי מים-מאט.',
    desc_en: 'Professional Hebrew explanation by Weizmann Institute educational arm.',
    url: 'https://davidson.org.il/read-experience/sciencepanorama/%D7%94%D7%AA%D7%90%D7%95%D7%A0%D7%94-%D7%94%D7%92%D7%A8%D7%A2%D7%99%D7%A0%D7%99%D7%AA-%D7%94%D7%A7%D7%A9%D7%94-%D7%91%D7%99%D7%95%D7%AA%D7%A8/', year: 2019 },
  { cat: 'sci', icon: '🔬', title: 'Chernobyl Forum (IAEA/WHO/UNDP) 2005', subtitle: 'מורשת צ׳רנוביל',
    desc_he: 'דוח משותף של 8 סוכנויות או״ם. הסיכום הסמכותי של ההשפעות הבריאותיות והסביבתיות לאחר 20 שנה.',
    desc_en: 'Joint report by 8 UN agencies. Authoritative summary of health and environmental effects 20 years after.',
    url: 'https://www.iaea.org/sites/default/files/chernobyl.pdf', year: 2005 },
  { cat: 'sci', icon: '🔬', title: 'Cardis et al. — השלכות סרטן (2006)', subtitle: 'IJC',
    desc_he: 'מאמר אקדמי המעריך 16,000 מקרי סרטן עודפים באירופה כתוצאה מצ׳רנוביל בעשורים הקרובים.',
    desc_en: 'Academic paper estimating 16,000 excess cancer cases in Europe over coming decades.',
    url: 'https://onlinelibrary.wiley.com/doi/10.1002/ijc.22037', year: 2006 },
];

export const SRC_CAT: Record<string, { c: string; he: string; en: string }> = {
  iaea: { c: '#c8a44e', he: 'IAEA', en: 'IAEA' },
  unscear: { c: '#22c55e', he: 'UNSCEAR', en: 'UNSCEAR' },
  who: { c: '#06b6d4', he: 'WHO', en: 'WHO' },
  nrc: { c: '#a855f7', he: 'NRC', en: 'NRC US' },
  book: { c: '#f59e0b', he: 'ספרים', en: 'Books' },
  doc: { c: '#ef4444', he: 'דוקומנטרי', en: 'Documentaries' },
  web: { c: '#94a3b8', he: 'אתרים', en: 'Websites' },
  sci: { c: '#06b6d4', he: 'מחקר אקדמי', en: 'Academic' },
};

// =================== TOC SECTIONS ===================
export const SECTIONS = [
  { id: 'hero', he: 'פתיחה', en: 'Intro', emoji: '🏠' },
  { id: 'timeline', he: 'ציר זמן', en: 'Timeline', emoji: '📅' },
  { id: 'reactor-general', he: 'איך כור גרעיני עובד', en: 'How a Nuclear Reactor Works', emoji: '⚛' },
  { id: 'rbmk', he: 'הכור והכשלים', en: 'The Reactor & Its Flaws', emoji: '☢' },
  { id: 'responders', he: 'הראשונים על הגג', en: 'The First on the Roof', emoji: '🔥' },
  { id: 'response', he: 'הליקווידטורים', en: 'Liquidators', emoji: '🚒' },
  { id: 'casualties', he: 'נפגעים', en: 'Casualties', emoji: '🕯' },
  { id: 'radiation', he: 'קרינה', en: 'Radiation', emoji: '📡' },
  { id: 'glossary', he: 'מונחים', en: 'Glossary', emoji: '📖' },
  { id: 'sources', he: 'מקורות', en: 'Sources', emoji: '📚' },
  { id: 'presentation', he: 'מצגת', en: 'Presentation', emoji: '🎯' },
  { id: 'infographic', he: 'אינפוגרפיקה', en: 'Infographic', emoji: '🎨' },
];
