// All data in one place. Bilingual HE/EN.

export const C = {
  ink: '#0a0e1a',
  navy: '#162040',
  gold: '#c8a44e',
  gL: '#e8d5a0',
  danger: '#ef4444',
  blue: '#06b6d4',
  green: '#22c55e',
  amber: '#f59e0b',
  purple: '#a855f7',
  white: '#ffffff',
};

// =================== TIMELINE (1971-2016) ===================
export const TIMELINE = [
  { date: '1971', he: 'תחילת בניית התחנה', en: 'Construction begins', cat: 'build',
    desc_he: 'הוחלט להקים את תחנת הכוח הגרעינית "ולדימיר איליץ׳ לנין" ליד נהר פריפיאט באוקראינה הסובייטית, 130 ק״מ צפונית לקייב.',
    desc_en: 'Decision to build the V.I. Lenin Nuclear Power Plant near the Pripyat River in Soviet Ukraine, 130 km north of Kyiv.' },
  { date: '1977', he: 'יחידה 1 — תחילת פעולה', en: 'Unit 1 begins operation', cat: 'build',
    desc_he: 'הכור הראשון מתחיל לייצר חשמל. RBMK-1000 — הספק נומינלי 1,000 MWe. תחנה זו נחשבה לאחת המתקדמות באיחוד הסובייטי.',
    desc_en: 'First reactor begins generating electricity. RBMK-1000 — nominal output 1,000 MWe.' },
  { date: 'דצמבר 1983', he: 'יחידה 4 — תחילת פעולה', en: 'Unit 4 begins operation', cat: 'build',
    desc_he: 'יחידה 4 (זו שתתפוצץ ב-1986) מתחילה לייצר חשמל. בנייתה הואצה כדי לעמוד ביעדי תכנית ה-5 שנים — חלק מהבדיקות נדחו.',
    desc_en: 'Unit 4 (the one that will explode in 1986) begins operation. Construction was rushed to meet 5-year plan deadlines.' },
  { date: '1983', he: '⚠ פגם המוטות התגלה — באיגנלינה', en: '⚠ Rod flaw discovered — Ignalina', cat: 'warn',
    desc_he: 'בכור RBMK באיגנלינה (ליטא) דווח על "השפעה חיובית של עצירת חירום" — תוספת תגובתיות זמנית בעת לחיצת AZ-5. הדיווח לא הופץ למפעילים בצ׳רנוביל.',
    desc_en: 'At Ignalina RBMK (Lithuania) the "positive scram effect" was reported. Report was NOT distributed to Chernobyl operators.' },
  { date: '1982-1985', he: '⚠ שלושה ניסויי טורבינה קודמים נכשלו', en: '⚠ Three previous turbine tests FAILED', cat: 'warn',
    desc_he: 'מטרת ניסוי הטורבינה: בעת תקלה בכור, 3 גנרטורי הדיזל לוקחים ~דקה לעלות — בזמן הזה משאבות הקירור ללא חשמל. רעיון: להשתמש באנרגיית ההתמדה של הטורבינה כדי לגשר על הפער. 3 ניסויים קודמים נכשלו. הניסוי הרביעי תוכנן ל-25/4/1986.',
    desc_en: 'Purpose of turbine test: when reactor fails, 3 diesel generators take ~1 minute to come online — during which cooling pumps lose power. Idea: use turbine inertia to bridge the gap. 3 previous tests failed. Fourth test scheduled for 25/4/1986.' },
  { date: '25/4/1986 01:06', he: 'הכנות לניסוי הטורבינה (ניסוי #4)', en: 'Turbine test preparation (Test #4)', cat: 'pre',
    desc_he: 'ניסוי בטיחות הרביעי בסדרה — הקודמים נכשלו. הספק מתחיל לרדת מ-3,200 MWt. תחנת צ׳רנוביל הפיקה 4,000 MW מ-4 כורים פעילים (+2 בבנייה). לעומת זאת, אורות רבין בחדרה — הגדולה בישראל — מפיקה 2,600 MW.',
    desc_en: 'Fourth test in series — earlier ones failed. Power begins reduction from 3,200 MWt. Chernobyl plant produced 4,000 MW from 4 active reactors (+2 in construction). For comparison: Israel\'s largest plant Orot Rabin produces 2,600 MW.' },
  { date: '25/4 14:00', he: '🚨 ECCS נותקה', en: '🚨 ECCS disabled', cat: 'warn',
    desc_he: 'מערכת קירור החירום נותקה ידנית כדי לא להפריע לניסוי. הפרת רישיון. הניסוי נדחה ב-9 שעות בגלל דרישת רשת החשמל.',
    desc_en: 'ECCS manually disabled to not interfere with test. License violation. Test delayed 9 hours due to grid demand.' },
  { date: '26/4 00:28', he: '⚠ קריסה ל-30 MWt', en: '⚠ Crash to 30 MWt', cat: 'warn',
    desc_he: 'שגיאת מפעיל גורמת לקריסת הספק. הרעלת קסנון מסיבית. הצוות שולף מוטות בכוח כדי לחזור לאחוזי הפעולה — נשארו רק 8 מתוך 211.',
    desc_en: 'Operator error causes power crash. Massive xenon poisoning. Crew forcibly withdraws rods — only 8 out of 211 remain.' },
  { date: '26/4 01:23:40', he: '🔴 הפיצוץ', en: '🔴 EXPLOSION', cat: 'disaster',
    desc_he: 'AZ-5 הופעל (לא ידוע בוודאות אם ע״י מפעיל או מערכת אוטומטית). תוך 7 שניות שני פיצוצים הורסים את יחידה 4. גג של ~1,000 ט׳ + מגן עליון "סכמה E" של 2,000 ט׳ נזרקים. הליבה חשופה. שריפת גרפיט מתחילה — תימשך 9 ימים.',
    desc_en: 'AZ-5 activated (not certain if by operator or automatic system). Within 7 seconds two explosions destroy Unit 4. ~1,000 t roof + 2,000 t "Schema E" upper bio-shield ejected. Core exposed. Graphite fire begins — will burn 9 days.' },
  { date: '26/4 01:28', he: 'הכבאים מגיעים', en: 'Firefighters arrive', cat: 'response',
    desc_he: '14 כבאים בראשות לוטננט פראבּיק מגיעים בעקבות שריפת הגג. ללא הגנת קרינה — לא הודיעו להם על הקרינה. רובם ימותו תוך שבועות.',
    desc_en: '14 firefighters led by Lt. Pravik arrive responding to roof fire. No radiation protection. Most will die within weeks.' },
  { date: '26/4 05:00', he: 'שריפת הגג כובתה', en: 'Roof fire extinguished', cat: 'response',
    desc_he: 'שריפות הגג והבניין כובו. אבל הליבה הגרפיטית עצמה בוערת ב-2,500°C ומשחררת רדיואקטיביות לאוויר במשך תשעה ימים.',
    desc_en: 'Roof and building fires extinguished. But graphite core burns at 2,500°C, releasing radioactivity for nine days.' },
  { date: '27/4 14:00', he: 'פינוי פריפיאט', en: 'Pripyat evacuation', cat: 'evac',
    desc_he: '1,200 אוטובוסים מפנים 49,000 תושבי פריפיאט תוך 3 שעות. ההודעה: "חזרו תוך 3 ימים". איש לא חזר לעולם.',
    desc_en: '1,200 buses evacuate 49,000 Pripyat residents within 3 hours. Announcement: "Return in 3 days". No one ever returned.' },
  { date: '28/4', he: 'שבדיה מתריעה לעולם', en: 'Sweden alerts the world', cat: 'global',
    desc_he: 'תחנת הכוח פורסמרק בשבדיה מזהה קרינה גבוהה על נעלי עובדים. ההגנה הסובייטית קורסת — העולם מגלה.',
    desc_en: 'Forsmark plant in Sweden detects high radiation on workers shoes. Soviet cover-up collapses — world finds out.' },
  { date: '2-10/5', he: 'הפלת חול ובור על הליבה', en: 'Sand and boron drops on core', cat: 'response',
    desc_he: '5,000 טון חול, חימר, עופרת ובור הוטלו ב-1,800 גיחות מסוקים על הליבה הבוערת. טייסי המסוקים ספגו מנות קרינה גבוהות.',
    desc_en: '5,000 tons of sand, clay, lead, and boron dropped in 1,800 helicopter sorties. Pilots received high radiation doses.' },
  { date: '4-6/5', he: 'שלושת המתנדבים', en: 'The Three Volunteers', cat: 'response',
    desc_he: 'אננקו, בז׳פאלוב ובארנוב צוללים למאגר מים מתחת לכור כדי לפתוח שסתום ולמנוע פיצוץ קיטור משני שעלול היה להגדיל את האסון פי 10.',
    desc_en: 'Ananenko, Bezpalov, and Baranov dive into water reservoir under reactor to open valve and prevent secondary steam explosion that could have multiplied disaster 10×.' },
  { date: '6/5', he: 'שריפת הגרפיט הסתיימה', en: 'Graphite fire extinguished', cat: 'response',
    desc_he: '9 ימים אחרי הפיצוץ, השריפה כובתה. סך כל הקרינה ששוחררה: 5,300 PBq — בערך 400 פעמים פצצת הירושימה מבחינת חומר רדיואקטיבי.',
    desc_en: '9 days after explosion, fire extinguished. Total radiation released: 5,300 PBq — ~400× Hiroshima bomb in radioactive material.' },
  { date: '5-11/1986', he: 'בניית הסרקופג הראשון', en: 'First Sarcophagus built', cat: 'build',
    desc_he: '600,000 ליקווידטורים בונים את "Object Shelter" — סרקופג בטון על הריסות הכור. תכנון לעמידות 30 שנה. הסתיים בנובמבר 1986.',
    desc_en: '600,000 liquidators build Object Shelter — concrete sarcophagus over reactor ruins. Designed for 30-year lifespan.' },
  { date: '1986-1989', he: 'מבצע ביו-רובוטים', en: 'Operation Bio-Robots', cat: 'response',
    desc_he: 'אחרי שרובוטים גרמניים נכשלו (אלקטרוניקה נשרפה מהקרינה), 3,400 חיילים סובייטיים שוגרו בנפרד לגג למשך 40-90 שניות כל אחד לפינוי גרפיט בידיים.',
    desc_en: 'After German robots failed (electronics burned by radiation), 3,400 Soviet soldiers were dispatched individually for 40-90 seconds each.' },
  { date: '29/11/2016', he: 'הסגירה החדשה (NSC)', en: 'New Safe Confinement', cat: 'build',
    desc_he: 'הסגירה החדשה — קונסטרוקציה מתכת הגדולה בעולם, גובה 108 מ׳, משקל 36,000 ט׳ — הוסגה על הסרקופג הישן. מתוכננת ל-100 שנה.',
    desc_en: 'New Safe Confinement — world\'s largest mobile metal structure, 108m tall, 36,000 t — slid over old sarcophagus. Designed for 100 years.' },
];

export const TL_CAT: Record<string, { c: string; he: string; en: string }> = {
  build: { c: '#94a3b8', he: 'בנייה', en: 'Construction' },
  warn: { c: '#f59e0b', he: 'אזהרה', en: 'Warning' },
  pre: { c: '#06b6d4', he: 'טרום-אסון', en: 'Pre-Disaster' },
  disaster: { c: '#dc2626', he: 'אסון', en: 'Disaster' },
  response: { c: '#22c55e', he: 'תגובה', en: 'Response' },
  evac: { c: '#a855f7', he: 'פינוי', en: 'Evacuation' },
  global: { c: '#06b6d4', he: 'גלובלי', en: 'Global' },
};

// =================== INSAG-7 — 10 STEPS ===================
export const INSAG = [
  { time: '01:06', mood: 'normal',
    he: 'הספק יורד לקראת הניסוי', en: 'Power drops for test',
    simple_he: 'הצוות מתחיל להוריד את עוצמת הכור כדי לבצע ניסוי בטיחות שתוכנן 4 שנים מראש.',
    simple_en: 'Crew begins lowering reactor power to perform a safety test planned 4 years in advance.',
    pro_he: 'התחלת הורדה מ-3,200 MWt ל-1,600 MWt בקצב מבוקר. תוכנית הניסוי: בדיקת יכולת ה-coastdown של טורבוגנרטור 8 לאספקת חשמל למשאבות הקירור הראשיות (MCP) למשך ~45 שניות עד שהגנרטורי דיזל החירום עולים. רישיון התקין דרש את הניסוי לפני אישור פעולה מסחרית מלאה.',
    pro_en: 'Power reduction from 3,200 MWt to 1,600 MWt at controlled rate. Test plan: verify turbogenerator 8 coastdown capability to power Main Circulation Pumps (MCPs) for ~45 seconds until emergency diesels come online.' },
  { time: '14:00', mood: 'normal',
    he: 'ECCS מנותקת', en: 'ECCS disconnected',
    simple_he: 'מערכת בטיחות חשובה מאוד מנותקת ידנית כדי לא להפריע לניסוי. זו הפרת חוק.',
    simple_en: 'A critical safety system is manually disconnected to not interfere with the test. This was a license violation.',
    pro_he: 'מערכת קירור החירום (Emergency Core Cooling System / ECCS) מנותקת ידנית מסיבת "מניעת הפעלה לא רצויה במהלך הניסוי". הפרת תקנון תפעול בולטת. רגולטור חיצוני מרשת אוקראינה דורש אספקת חשמל נוספת — הניסוי נדחה ב-9 שעות.',
    pro_en: 'ECCS disconnected manually citing "prevention of unwanted activation during test." Major operating license violation. Ukrainian grid regulator demands continued power supply — test delayed 9 hours.' },
  { time: '23:10', mood: 'caution',
    he: 'משמרת לילה — לא מוכנה', en: 'Night shift — not prepared',
    simple_he: 'המשמרת המקורית שהתאמנה על הניסוי כבר עברה הביתה. המשמרת החדשה לא מודרכת.',
    simple_en: 'The original shift trained for the test went home. The new shift is not briefed.',
    pro_he: 'משמרת היום (סוקולוב) שתודרכה על תוכנית הניסוי כבר חזרה הביתה. משמרת לילה תחת המהנדס הראשי אנטולי דיאטלוב מקבלת תוכנית ניסוי מורכבת ללא הכשרה מסודרת. המפעיל הראשי לאוניד טופטונוב — בעל ניסיון של 4 חודשים בתחנה.',
    pro_en: 'Day shift (Sokolov) trained for test program had returned home. Night shift under chief engineer Anatoly Dyatlov receives complex test plan without proper briefing. Senior operator Leonid Toptunov — only 4 months\' experience.' },
  { time: '00:28', mood: 'danger',
    he: 'קריסה ל-30 MWt — הרעלת קסנון', en: 'Crash to 30 MWt — Xenon poison',
    simple_he: 'בגלל שגיאת מפעיל ההספק מתרסק. גז קסנון רדיואקטיבי שמייוצר באופן טבעי דועך את הכור. האופציה הבטוחה הייתה לכבות ל-2-3 ימים — לא נבחרה.',
    simple_en: 'Due to operator error, power crashes. Naturally-produced radioactive xenon gas suppresses the reactor. Safe option was to shut down for 2-3 days — not chosen.',
    pro_he: 'טופטונוב לוחץ בטעות על מתג מקומי-לאוטומטי. ההספק קורס מ-1,600 ל-30 MWt. במצב זה Xe-135 (ספיח ניוטרונים החזק ביותר הידוע, נוצר מיוד-135 שתוצר ביקוע נפוץ) הורג את הליבה. בכור פעיל, Xe-135 בולע ניוטרון והופך ל-Xe-136 לא-רעיל. אופציה בטוחה: כיבוי 2-3 ימים עד פירוק קסנון. אך המהנדס הראשי דיאטלוב מורה: "תרים את ההספק חזרה!" — בניגוד לתקנות.',
    pro_en: 'Toptunov accidentally clicks local-to-auto switch. Power crashes from 1,600 to 30 MWt. In this state Xe-135 (strongest known neutron absorber, produced from I-135 — common fission product) chokes the core. In an active reactor, Xe-135 absorbs a neutron becoming non-toxic Xe-136. Safe option: shut down 2-3 days until xenon decay. But chief Dyatlov orders: "Bring power back up!" — against regulations.' },
  { time: '01:00', mood: 'danger',
    he: 'מוטות נשלפים בכוח — ORM=8', en: 'Rods forcibly withdrawn — ORM=8',
    simple_he: 'הצוות שולף כמעט את כל מוטות הבקרה כדי להחזיר את ההספק. זה משאיר את הכור חסר הגנה.',
    simple_en: 'Crew withdraws almost all control rods to restore power. This leaves the reactor defenseless.',
    pro_he: 'מתוך 211 מוטות, רק 8 נותרו בליבה (ORM=8). מינימום מותר על פי תקנון: 30 (ORM=30 ≈ 1.5β reserve). בלי מוטות בליבה, אין יכולת חוצץ לעצור עליית הספק. ההספק מתייצב ב-200 MWt — לא יציב.',
    pro_en: 'Of 211 rods, only 8 remain in core (ORM=8). Minimum allowed per regulations: 30 (ORM=30 ≈ 1.5β reserve). Without rods in core, no buffer capacity exists to halt power rise. Power stabilizes at 200 MWt — unstable.' },
  { time: '01:23:04', mood: 'critical',
    he: 'תחילת הניסוי', en: 'Test begins',
    simple_he: 'הניסוי מתחיל. אספקת החשמל לטורבינה מנותקת והיא מתחילה לרוץ באופן עצמאי.',
    simple_en: 'Test begins. Power to turbine cut, turbine begins to coast down independently.',
    pro_he: 'שסתום הקיטור לטורבוגנרטור 8 נסגר — Coastdown מתחיל. 4 משאבות קירור ראשיות (MCP) מואטות עם הטורבינה. זרימת מים לליבה יורדת. בועות קיטור (voids) מתחילות להיווצר בערוצי הקירור.',
    pro_en: 'Steam valve to turbogenerator 8 closes — Coastdown begins. 4 Main Circulation Pumps (MCPs) slow with turbine. Water flow to core decreases. Steam voids begin forming in cooling channels.' },
  { time: '01:23:40', mood: 'explosion',
    he: 'AZ-5 נלחץ — האפקט החיובי', en: 'AZ-5 pressed — Positive scram',
    simple_he: 'כפתור עצירת החירום נלחץ — לא ידוע בוודאות אם על ידי מפעיל או מערכת אוטומטית. אבל בגלל פגם בעיצוב, המוטות גורמים לפיצוץ במקום לעצור.',
    simple_en: 'Emergency scram button pressed — uncertain whether by operator or automatic system. But due to design flaw, rods cause explosion instead of stopping.',
    pro_he: 'כפתור AZ-5 (Avariynaya Zashchita) נלחץ — מתחיל החדרת 211 מוטות. מקור הלחיצה לא ידוע בוודאות (החלטת אקיימוב/טופטונוב או מערכת בטיחות אוטומטית). הקצוות הגרפיטיים של המוטות (3 מ׳ עליון) דוחפים מים החוצה תחילה — תוספת תגובתיות חיובית במקום שלילית. בליבה ריקה ב-ORM=8 וחללות גבוהה (positive void coeff +4.7β), הכור עובר לקריטיות פרומפטית בתוך 1.5 שניות.',
    pro_en: 'AZ-5 (Avariynaya Zashchita) pressed — 211 rods begin insertion. Source of press uncertain (Akimov/Toptunov decision or auto safety system). Rods\' graphite tips (upper 3m) displace water first — initiating positive instead of negative reactivity. With core depleted to ORM=8 and high voiding (positive void coeff +4.7β), reactor goes prompt-critical within 1.5 seconds.' },
  { time: '01:23:43', mood: 'apocalypse',
    he: 'הספק זינק ל-30,000 MWt', en: 'Power surges to 30,000 MWt',
    simple_he: 'בתוך 3 שניות הכור מייצר פי 100 מההספק הנורמלי שלו. זו תגובת שרשרת בלתי נשלטת.',
    simple_en: 'Within 3 seconds reactor produces 100× normal power. Uncontrolled chain reaction.',
    pro_he: 'ההספק עולה אקספוננציאלית: 200 → 530 → 30,000+ MWt. דלק האורניום נמס. תעלות הלחץ של זירקאלוי קורסות. לחץ הקיטור ב-1,661 ערוצים זינק מ-65 atm ל->600 atm. הפיצוץ הראשון: התפוצצות קיטור, ב-01:23:45.',
    pro_en: 'Power rises exponentially: 200 → 530 → 30,000+ MWt. Uranium fuel melts. Zircaloy pressure tubes collapse. Steam pressure in 1,661 channels surges from 65 atm to >600 atm. First explosion: steam blast at 01:23:45.' },
  { time: '01:23:45', mood: 'apocalypse',
    he: 'הפיצוץ הראשון — קיטור', en: 'First explosion — Steam',
    simple_he: 'הפיצוץ הראשון: ככל הנראה קיטור בלחץ עצום. גג של ~1,000 ט׳ נזרק לאוויר.',
    simple_en: 'First explosion: most likely massive steam pressure. ~1,000 ton roof blasted into air.',
    pro_he: 'פיצוץ ראשון — שתי תיאוריות: (1) פיצוץ קיטור — אידוי כל מי הקירור הקיימים בליבה גרם להצטברות לחץ עצום. (2) פיצוץ נוקלאו-תרמי. גג של ~1,000 ט׳ + מגן עליון "סכמה E" של 2,000 ט׳ נזרקים. תעלות הלחץ נחתכות. אטמוספירה חודרת לליבה ופוגשת זירקאלוי חם ב-2,500°C. תגובה Zr+H₂O → ZrO₂+H₂ מייצרת מימן.',
    pro_en: 'First explosion — two theories: (1) Steam explosion — vaporization of all coolant in core caused massive pressure buildup. (2) Nuclear-thermal explosion. ~1,000 t roof + 2,000 t "Schema E" upper bio-shield ejected. Pressure tubes severed. Atmosphere enters core, meeting hot Zircaloy at 2,500°C. Reaction Zr+H₂O → ZrO₂+H₂ generates hydrogen.' },
  { time: '01:23:47', mood: 'apocalypse',
    he: 'הפיצוץ השני — מימן/חמצן', en: 'Second explosion — Hydrogen/Oxygen',
    simple_he: 'הפיצוץ השני, חזק יותר. הכור נחשף לחלוטין. שריפת גרפיט מתחילה ותימשך 9 ימים.',
    simple_en: 'Second, stronger explosion. Reactor fully exposed. Graphite fire begins, will burn 9 days.',
    pro_he: '2 שניות אחרי הראשון — פיצוץ שני, ככל הנראה מימן/חמצן. הליבה נפתחת לחלוטין. ~7 טון דלק מועף לשמיים. גרפיט במגע עם אוויר ב-2,500°C מתלקח — שריפה שתימשך 9 ימים. שחרור 5,300 PBq של תוצרי ביקוע. 134 ליקווידטורים מאובחנים ב-ARS חמורה תוך שעות.',
    pro_en: '2 seconds after first — second blast, likely hydrogen/oxygen. Core fully opens. ~7 tons of fuel ejected skyward. Graphite ignites in air at 2,500°C — fire that will burn 9 days. Release of 5,300 PBq fission products. 134 liquidators diagnosed with severe ARS within hours.' },
];

// =================== RBMK COMPONENTS ===================
export const RBMK_COMP = [
  { id: 'vessel', he: 'מכל לחץ', en: 'Pressure Vessel',
    simple_he: 'הקופסה שעוטפת את הכור. ב-RBMK הסובייטי לא הייתה לה הגנה כפולה כמו בכורים מערביים.',
    simple_en: 'The box that wraps the reactor. The Soviet RBMK lacked double containment like Western reactors.',
    pro_he: 'מכל פלדה-בטון 26 מ׳ × 21.6 מ׳. ב-RBMK אין containment חיצוני. ב-PWR/BWR מערביים יש כיפת בטון נוספת מסוגלת לעמוד בהשתחררות מלאה. זה היה כשל תכן קריטי.',
    pro_en: 'Steel-concrete vessel 26m × 21.6m. RBMK lacks outer containment. Western PWR/BWR have additional concrete dome capable of withstanding full release. Critical design flaw.' },
  { id: 'graphite', he: 'גרפיט מאט', en: 'Graphite Moderator',
    simple_he: 'בלוקי גרפיט (כמו עפרון) שמאיטים ניוטרונים כדי שיוכלו לבקע אורניום. ב-RBMK יש 1,700 טון גרפיט.',
    simple_en: 'Graphite blocks (like pencil lead) that slow neutrons to enable uranium fission. RBMK has 1,700 tons of graphite.',
    pro_he: '1,700 טון גרפיט יוצרים את הליבה הקובית. שימש למאט (moderator). בעל מקדם תגובתיות חיובי בטמפרטורה גבוהה. בעירה ב-2,500°C עם אוויר שיחרר את ה-Cs-137 רוב התקופה.',
    pro_en: '1,700 tons of graphite forming cubic core. Functions as moderator. Has positive temperature reactivity coefficient. Combustion at 2,500°C with air released most of Cs-137 over the burning period.' },
  { id: 'fuel', he: 'מוטות דלק', en: 'Fuel Rods',
    simple_he: 'מוטות אורניום (UO₂) ב-2% העשרה. כל ליבה מכילה 1,661 מוטות. אלה המקור של תגובת השרשרת.',
    simple_en: 'Uranium (UO₂) rods at 2% enrichment. Each core contains 1,661 rods. Source of chain reaction.',
    pro_he: 'דלק UO₂ מועשר ב-2.0% U-235. 1,661 ערוצי דלק. אורך מוט: 7 מ׳. תכולת אורניום בליבה: 192 ט׳. בפיצוץ: ~7 ט׳ דלק נפלט לאטמוספירה — הראשונה בהיסטוריה של פיצוץ כור פעיל.',
    pro_en: 'UO₂ fuel enriched to 2.0% U-235. 1,661 fuel channels. Rod length: 7m. Core uranium: 192 tons. In explosion: ~7 tons fuel ejected to atmosphere — first in history of operating reactor explosion.' },
  { id: 'rods', he: 'מוטות בקרה', en: 'Control Rods',
    simple_he: 'מוטות שעשויים מבורון, מוחדרים לליבה כדי להאט/לעצור את התגובה. ב-RBMK היה להם פגם קטלני: קצה גרפיט.',
    simple_en: 'Boron rods inserted to slow/stop reaction. RBMK had a fatal flaw: graphite tip.',
    pro_he: '211 מוטות B₄C/Dy₂TiO₅. החדרה מלאה לוקחת 18-21 שניות (לעומת ~3 שניות בכורים מערביים). פגם קריטי: קצה עליון של 4.5 מ׳ גרפיט מקטין את הספיחה לפני שספח הבורון מגיע — "אפקט החדרה חיובי" שגרם לפיצוץ.',
    pro_en: '211 B₄C/Dy₂TiO₅ rods. Full insertion: 18-21 sec (vs ~3 sec in Western reactors). Critical flaw: 4.5m graphite tip reduces absorption before boron absorber arrives — "positive scram effect" that triggered explosion.' },
  { id: 'drum', he: 'תופי הפרדה', en: 'Steam Separator Drums',
    simple_he: '4 גלילים גדולים שמפרידים את הקיטור מהמים אחרי שהמים התחממו בכור.',
    simple_en: '4 large cylinders separating steam from water after water heats in reactor.',
    pro_he: '4 גלילים אופקיים, 30 מ׳ × 2.6 מ׳. הפרדה ביוגרבית של מי-קיטור (תערובת 14% קיטור) ל: קיטור יבש לטורבינה, מים בחזרה דרך MCP לליבה. לחץ פעולה: 65 atm.',
    pro_en: '4 horizontal drums, 30m × 2.6m. Gravimetric separation of steam-water mixture (14% steam) into: dry steam to turbine, water back through MCP to core. Operating pressure: 65 atm.' },
  { id: 'mcp', he: 'משאבות קירור ראשיות (MCP)', en: 'Main Circulation Pumps (MCP)',
    simple_he: '8 משאבות שמזרימות מים דרך הכור לקירור. ב-26/4 כל ה-8 הופעלו במקביל — זה לא היה מומלץ.',
    simple_en: '8 pumps circulating water through reactor for cooling. On 26/4 all 8 operated simultaneously — not recommended.',
    pro_he: '8 משאבות צנטריפוגליות, 6 פעילות + 2 רזרבה. ב-26/4 כל ה-8 הופעלו לדרישת הניסוי. זרימה מוגברת הקטינה את ההפרש בין כניסה ליציאה (subcooling), הגדילה רגישות ל-void coefficient.',
    pro_en: '8 centrifugal pumps, 6 active + 2 reserve. On 26/4 all 8 operated per test requirement. Increased flow reduced inlet-outlet differential (subcooling), increased sensitivity to void coefficient.' },
  { id: 'turbine', he: 'טורבוגנרטור', en: 'Turbogenerator',
    simple_he: 'מתקן שממיר את הקיטור מהכור לחשמל. הניסוי בדק האם הוא יכול לספק חשמל בזמן כיבוי.',
    simple_en: 'Device converting reactor steam to electricity. Test was checking if it could supply power while shutting down.',
    pro_he: '2 טורבוגנרטורים מסוג K-500-65/3000, 500 MWe כל אחד. ניסוי 26/4 בחן את יכולת ה-coastdown של גנרטור 8 לאספקת חשמל למשאבות הקירור למשך 45 שניות עד שגנרטורי דיזל החירום עולים.',
    pro_en: '2 K-500-65/3000 turbogenerators, 500 MWe each. Test on 26/4 was verifying generator 8 coastdown capability to supply MCPs for 45 sec until emergency diesels online.' },
  { id: 'az5', he: 'AZ-5 — כפתור עצירה', en: 'AZ-5 — Scram Button',
    simple_he: 'כפתור עצירת חירום אדום. בפעולה רגילה אמור לעצור את הכור תוך שניות. ב-26/4 הוא גרם לפיצוץ.',
    simple_en: 'Red emergency stop button. In normal operation should stop reactor within seconds. On 26/4 it triggered the explosion.',
    pro_he: 'AZ-5 (Avariynaya Zashchita-5) — מערכת עצירת חירום שמחדירה את כל 211 המוטות. ב-26/4 בשעה 01:23:40 לחיצה על AZ-5 גרמה לאפקט החדרה חיובי בכור עם ORM=8 ו-void coefficient גבוה. הכור הפך לסופר-קריטי פרומפטי תוך 1.5 שניות.',
    pro_en: 'AZ-5 (Avariynaya Zashchita-5) — emergency shutdown inserting all 211 rods. On 26/4 01:23:40 AZ-5 press triggered positive scram effect in core with ORM=8 and high void coeff. Reactor went prompt supercritical within 1.5 seconds.' },
  { id: 'eccs', he: 'ECCS — קירור חירום', en: 'ECCS — Emergency Core Cooling',
    simple_he: 'מערכת גיבוי שמציפה את הכור במים אם הקירור הראשי נכשל. ב-25/4 היא נותקה ידנית — הפרת רישיון.',
    simple_en: 'Backup system flooding reactor with water if primary cooling fails. On 25/4 manually disconnected — license violation.',
    pro_he: 'Emergency Core Cooling System — מציף את הליבה במים אם זרימת הקירור הראשית נופלת מתחת ל-50%. ב-25/4 14:00 דיאטלוב הורה לנתק את ECCS כדי לא להפריע לניסוי. הפרת רישיון תפעולי בולטת.',
    pro_en: 'Emergency Core Cooling System — floods core with water if primary cooling drops below 50%. On 25/4 14:00 Dyatlov ordered ECCS disconnect to not interfere with test. Major operating license violation.' },
  { id: 'shield', he: 'מגן ביולוגי "סכמה E"', en: 'Bio-Shield "Schema E"',
    simple_he: 'לוח פלדה-בטון 2,000 טון שעוטף את החלק העליון של הכור. בפיצוץ הוא נזרק לאוויר ונחת בזווית.',
    simple_en: '2,000-ton steel-concrete plate covering reactor top. In explosion ejected to air, landed at angle.',
    pro_he: 'לוח עליון מסיבי בקוטר 17 מ׳, עובי 3 מ׳, משקל 2,000 ט׳. אמור היה לאטום את הליבה. בפיצוץ הראשון נזרק לאוויר עם המשך כלוב התעלות. נחת בזווית של ~15° מעל הליבה החשופה — נשאר ככה עד היום.',
    pro_en: 'Massive upper plate 17m diameter, 3m thick, 2,000 t. Should have sealed core. In first explosion ejected to air with cascade of channels. Landed at ~15° angle over exposed core — remains so today.' },
  { id: 'void', he: 'מקדם החללות (Void Coefficient)', en: 'Void Coefficient',
    simple_he: 'תכונה פיזיקלית של הכור: כשמים מתאדים לקיטור, ההספק עולה במקום לרדת. זה היה הפגם הקריטי ביותר. ברוב הכורים בעולם זה הפוך — מנגנון בטיחות מובנה.',
    simple_en: 'Physical property: when water vaporizes to steam, power rises instead of falls. Most critical flaw. In most reactors worldwide it\'s the opposite — built-in safety mechanism.',
    pro_he: 'מקדם תגובתיות חללות חיובי של +4.7β ב-RBMK. בכורי מים-מאט מערביים (PWR/BWR) — מים גם מאט וגם קירור: כשמים מתאדים → פחות מאט → תגובה יורדת → בטיחות מובנית. ב-RBMK הגרפיט הוא המאט והמים רק קירור (וסופחים ניוטרונים מעט). כשמים מתאדים → פחות ספיחה → תגובה עולה → טמפרטורה עולה → יותר קיטור → רגרסיה חיובית קטלנית.',
    pro_en: 'Positive void reactivity coefficient of +4.7β in RBMK. In Western water-moderated reactors (PWR/BWR), water serves as both moderator and coolant: vaporized water → less moderation → reaction drops → built-in safety. In RBMK, graphite is the moderator and water only the coolant (slightly absorbing neutrons). Vaporized water → less absorption → reactivity rises → temp rises → more steam → fatal positive feedback.' },
  { id: 'orm', he: 'ORM — מרווח תגובתיות מבצעי', en: 'ORM — Operational Reactivity Margin',
    simple_he: 'מספר מוטות הבקרה שצריכים להיות בליבה כל הזמן כרזרבה בטיחותית. מינימום מותר: 30. ב-26/4: 8 בלבד.',
    simple_en: 'Number of control rods that must remain in core as safety reserve. Allowed minimum: 30. On 26/4: only 8.',
    pro_he: 'Operational Reactivity Margin — מספר מוטות שולחנו של ידנית להחדרה לעצירת תגובתיות. מינימום על פי תקנון: 30 מוטות (≈1.5β). ב-01:23:40 הליבה הייתה ב-ORM=8 — כמעט ללא רזרבה. גורם מכריע לאסון.',
    pro_en: 'Operational Reactivity Margin — number of rods available for manual reactivity insertion. Regulatory minimum: 30 rods (≈1.5β). At 01:23:40 core was at ORM=8 — nearly no reserve. Decisive disaster factor.' },
  { id: 'diesel', he: 'גנרטורי דיזל חירום', en: 'Emergency Diesel Generators',
    simple_he: '3 גנרטורי דיזל פנימיים מספקים חשמל למשאבות הקירור אם הזרם לכור נכשל. אבל לוקח להם ~דקה לעלות — הסיבה לכל ניסוי הטורבינה.',
    simple_en: '3 internal diesel generators supply power to cooling pumps if reactor power fails. But take ~1 minute to start — the very reason for the turbine test.',
    pro_he: '3 גנרטורי דיזל בתוך מתחם הכור. תפקידם: לספק חשמל למשאבות הקירור (MCP) במקרה של אובדן זרם חיצוני. אבל זמן ההתנעה ~60 שניות. רעיון ניסוי הטורבינה: להשתמש באנרגיית ההתמדה (kinetic) של הטורבינה לגשר על דקת הביניים — להפעיל את ה-MCP על ידי גנרטור-טורבינה בעת coastdown. 3 ניסויים קודמים נכשלו (1982-1985). הניסוי הרביעי הוא שגרם לאסון.',
    pro_en: '3 diesel generators inside reactor compound. Purpose: supply power to MCPs in case of external power loss. But startup time ~60 seconds. Turbine test idea: use turbine kinetic inertia to bridge the gap minute — power MCPs from turbo-generator during coastdown. 3 previous tests failed (1982-1985). The fourth test caused the disaster.' },
  { id: 'xenon', he: 'הרעלת קסנון-135', en: 'Xenon-135 Poisoning',
    simple_he: 'גז קסנון-135 שמייוצר בתוך הליבה הוא בולע ניוטרונים החזק ביותר בעולם. בכור פעיל הוא נשרף — אבל בהספק נמוך הוא מצטבר ומדכא את הכור.',
    simple_en: 'Xenon-135 gas produced inside core is the strongest known neutron absorber. In an active reactor it burns up — but at low power it accumulates and chokes the reactor.',
    pro_he: 'תוצר ביקוע נפוץ של U-235: יוד-135 → בטא דעיכה → קסנון-135 (בעל זמן מחצית-חיים 9.2 שעות). הוא ספיח הניוטרונים החזק ביותר הידוע. בכור פעיל בהספק רגיל: Xe-135 + ניוטרון → Xe-136 (לא רעיל, יציב) — מאזן צריכה. בהספק נמוך: Xe-135 מצטבר. ב-26/4 הצטברות הקסנון מ-23:10-00:28 גרמה לקריסת ההספק. אופציה בטוחה: כיבוי 2-3 ימים עד דעיכה טבעית.',
    pro_en: 'Common fission product of U-235: Iodine-135 → beta decay → Xenon-135 (half-life 9.2 hours). Strongest known neutron absorber. In active reactor at normal power: Xe-135 + neutron → Xe-136 (non-toxic, stable) — consumption balance. At low power: Xe-135 accumulates. On 26/4 xenon buildup from 23:10 to 00:28 caused power crash. Safe option: shutdown 2-3 days for natural decay.' },
];

// =================== LIQUIDATOR GROUPS ===================
export const LIQUIDATORS = [
  { id: 'fire', icon: '🚒', he: 'הכבאים הראשונים', en: 'First Firefighters', count: '~30',
    lead: 'Lt. Vladimir Pravik · Lt. Viktor Kibenok',
    desc_he: '14 כבאים שהגיעו ב-01:28, ועוד שתי משמרות שהצטרפו. ללא הגנת קרינה — לא הודיעו להם. רובם מתו תוך שבועות מתסמונת קרינה חריפה (ARS) במוסקבה. פראבּיק וקיבנוק שניהם זכו לאחר מותם בתואר "גיבור ברית המועצות".',
    desc_en: '14 firefighters arrived at 01:28, plus two more shifts. No radiation protection — not informed. Most died within weeks from Acute Radiation Syndrome (ARS) in Moscow. Pravik and Kibenok received "Hero of the Soviet Union" posthumously.',
    risk: 'extreme', dose: '4-16 Gy' },
  { id: 'pilot', icon: '🚁', he: 'טייסי המסוקים', en: 'Helicopter Pilots', count: '~600',
    lead: 'Maj. Gen. Nikolai Antoshkin',
    desc_he: 'בוצעו 1,800 גיחות מסוק להפלת חול, חימר, עופרת ובור על הליבה הבוערת. הקרינה מעל הכור הגיעה ל-3,500 R/h. טייס אחד נהרג כש-Mi-8 התרסק על כבל בכרס בית הקרור ב-2/10/86.',
    desc_en: '1,800 helicopter sorties dropped sand, clay, lead, and boron on burning core. Radiation above reactor reached 3,500 R/h. One pilot died when Mi-8 crashed into cooling tower cable on 2 Oct 1986.',
    risk: 'extreme', dose: '0.5-2 Sv' },
  { id: 'tunnel', icon: '⛏', he: 'חופרי המנהרה', en: 'Tunnel Diggers', count: '~400',
    lead: 'Coal miners from Donbas + Tula',
    desc_he: 'חופרים ממוסקבה ואוקראינה חפרו מנהרה של 168 מטר מתחת לכור — דרך אדמה רוויית קרינה — כדי להתקין מערכת קירור שתמנע הריסה לתוך מי התהום. עבדו 24/7 במשמרות 3 שעות.',
    desc_en: 'Diggers from Moscow and Ukraine dug a 168-meter tunnel beneath the reactor — through radiation-saturated earth — to install cooling system preventing meltdown into groundwater. Worked 24/7 in 3-hour shifts.',
    risk: 'high', dose: '~0.3 Sv avg' },
  { id: 'volunt', icon: '🏊', he: 'שלושת המתנדבים', en: 'Three Volunteers', count: '3',
    lead: 'Alexei Ananenko · Valeri Bezpalov · Boris Baranov',
    desc_he: 'ב-4-6/5 שלושה מהנדסים צללו למאגר מים מתחת לכור הבוער כדי לפתוח שסתום ולמנוע פיצוץ קיטור משני שעלול היה להגדיל את האסון פי 10. בניגוד לאגדה — שלושתם שרדו. אננקו ובז׳פאלוב חיים עד היום (2026).',
    desc_en: 'On 4-6 May, three engineers dove into water reservoir below burning reactor to open valve and prevent secondary steam explosion that could have multiplied disaster 10×. Contrary to legend — all three survived. Ananenko and Bezpalov are alive today (2026).',
    risk: 'extreme', dose: 'survived' },
  { id: 'biorobot', icon: '🦾', he: '"ביו-רובוטים" — מנקי הגג', en: '"Bio-Robots" — Roof Cleaners', count: '~3,400',
    lead: '',
    desc_he: 'אחרי שרובוטים גרמניים נכשלו (האלקטרוניקה נשרפה מהקרינה), 3,400 חיילים ממילואים נשלחו לגג למשך 40-90 שניות בלבד כל אחד. כל חייל זרק 1-2 גושי גרפיט בעופרים — ואז ירץ למטה. הגנה: סינר עופרת, קסדה, מנ״פ.',
    desc_en: 'After German robots failed (electronics burned by radiation), 3,400 reservists were sent to the roof for only 40-90 seconds each. Each soldier threw 1-2 graphite chunks with shovels — then ran down.',
    risk: 'extreme', dose: '0.25 Sv per session' },
  { id: 'sarc', icon: '🏗', he: 'בוני הסרקופג', en: 'Sarcophagus Builders', count: '~200,000',
    lead: '',
    desc_he: 'בוני הסרקופג הראשון ("Object Shelter") שהוקם תוך 6 חודשים — מ-5/86 עד 11/86. השתמשו בשלט-רחוק להזרמת בטון, אבל חלק מהעבודה נדרשה ידנית. צריכת בטון: 400,000 מ"ק. צריכת פלדה: 7,300 ט׳.',
    desc_en: 'Builders of the first sarcophagus erected in 6 months — May to November 1986. Concrete consumed: 400,000 m³. Steel: 7,300 t.',
    risk: 'high', dose: '~0.1-0.5 Sv' },
  { id: 'evac', icon: '🚌', he: 'נהגי האוטובוסים', en: 'Bus Drivers', count: '~5,000',
    lead: '',
    desc_he: '1,200 אוטובוסים פינו 49,000 תושבי פריפיאט תוך 3 שעות ב-27/4. נהגי האוטובוסים שעברו דרך אזור הקרינה הבליעו מנות גבוהות.',
    desc_en: '1,200 buses evacuated 49,000 Pripyat residents within 3 hours on 27/4. Bus drivers passing through the radiation zone absorbed high doses.',
    risk: 'high', dose: '~0.05-0.2 Sv' },
  { id: 'decon', icon: '🧹', he: 'צוותי טיהור', en: 'Decontamination Teams', count: '~300,000',
    lead: '',
    desc_he: 'טיהור הקרקע, הבתים, הרכבים וכל פיסת אדמה באזור 30 ק״מ. שיטות: שטיפה במים מיוחדים, חיתוך וקבירה של אדמה עליונה (5 ס"מ), הריסת כפרים שלמים. 188 כפרים נקברו תחת אדמה.',
    desc_en: 'Decontamination of soil, houses, vehicles, and every patch of land in 30 km zone. 188 villages were buried under earth.',
    risk: 'high', dose: '~0.05-0.3 Sv' },
  { id: 'guard', icon: '🪖', he: 'משמרות ושמירה', en: 'Guards & Security', count: '~50,000',
    lead: '',
    desc_he: 'חיילים ששמרו על אזור ההדרה, מנעו לוטים, וניהלו מחסומים. גם אחרי הסיכון המיידי הסתיים, הם המשיכו לחיות באזור הקרינה במשך חודשים.',
    desc_en: 'Soldiers guarding the exclusion zone, preventing looting, and managing checkpoints.',
    risk: 'medium', dose: '~0.02-0.1 Sv' },
  { id: 'medic', icon: '⚕️', he: 'צוותים רפואיים', en: 'Medical Teams', count: '~20,000',
    lead: 'Dr. Angelina Guskova',
    desc_he: 'רופאים ואחיות שטיפלו בנפגעי ARS במוסקבה (בית חולים מס׳ 6) ובאזור עצמו. ד״ר גוסקובה הייתה הראשונה בעולם שטיפלה במספר כה גדול של נפגעי קרינה חריפה. השתלות מח עצם נכשלו ברובן.',
    desc_en: 'Doctors and nurses treating ARS victims in Moscow (Hospital No. 6) and on-site. Dr. Guskova was the first in the world to treat such a large number of acute radiation casualties.',
    risk: 'medium', dose: 'low contact' },
];

// =================== CASUALTIES & STATS ===================
export const CASUALTIES = {
  immediate: [
    { n: '2', he: 'הרוגים מיידיים בפיצוץ', en: 'Immediate explosion deaths', detail_he: 'אחד נמחץ בהריסות (Khodemchuk), השני (Shashenok) מצואב חמור', detail_en: 'One crushed in debris (Khodemchuk), one severely burned (Shashenok)' },
    { n: '134', he: 'אובחנו ב-ARS חריף', en: 'Diagnosed with severe ARS', detail_he: 'ליקווידטורים וכבאים שהובאו לבית חולים מס׳ 6 במוסקבה', detail_en: 'Liquidators and firefighters taken to Moscow Hospital No. 6' },
    { n: '28', he: 'מתו מ-ARS תוך 3 חודשים', en: 'Died from ARS within 3 months', detail_he: 'רובם הכבאים הראשונים שעלו על הגג', detail_en: 'Mostly first firefighters who climbed roof' },
    { n: '~31', he: 'הרוגים מאומתים מהאסון', en: 'Confirmed deaths from disaster', detail_he: 'IAEA + UNSCEAR נתון רשמי', detail_en: 'IAEA + UNSCEAR official figure' },
  ],
  longterm: [
    { n: '6,000+', he: 'מקרי סרטן בלוטת התריס בילדים', en: 'Childhood thyroid cancer cases', detail_he: 'בעיקר בבלארוס ואוקראינה. רובם נרפאו (ניתוח+טיפול). ~15 מתו עד 2005.', detail_en: 'Mainly Belarus and Ukraine. Most cured (surgery+treatment). ~15 died by 2005.' },
    { n: '~9,000', he: 'מקרי סרטן עודפים צפויים (UNSCEAR)', en: 'Expected excess cancer cases', detail_he: 'הערכה לטווח ארוך באזור המזוהם המידי', detail_en: 'Long-term estimate in immediate contaminated area' },
    { n: '16,000', he: 'מקרי סרטן עודפים באירופה (Cardis 2006)', en: 'Excess cancer cases in Europe', detail_he: 'הערכה ל-50 שנה הקרובות (מאמר IJC)', detail_en: 'Estimate over next 50 years (IJC paper)' },
    { n: '~10%', he: 'תמותה עודפת בקרב הליקווידטורים', en: 'Excess mortality among liquidators', detail_he: 'הערכת UNSCEAR אחרי 30 שנה', detail_en: 'UNSCEAR estimate after 30 years' },
  ],
  evac: [
    { n: '49,000', he: 'תושבי פריפיאט פונו', en: 'Pripyat residents evacuated', detail_he: '27/4/86, ב-1,200 אוטובוסים תוך 3 שעות', detail_en: '27/4/86, in 1,200 buses within 3 hours' },
    { n: '116,000', he: 'פונו מאזור 30 ק״מ ב-1986', en: 'Evacuated from 30km zone in 1986', detail_he: '88 כפרים פונו עד אוקטובר 1986', detail_en: '88 villages evacuated by October 1986' },
    { n: '~350,000', he: 'סך כל הפינויים בטווח הארוך', en: 'Total long-term resettlement', detail_he: 'מאוקראינה, בלארוס, רוסיה — UNSCEAR', detail_en: 'From Ukraine, Belarus, Russia — UNSCEAR' },
    { n: '188', he: 'כפרים נקברו תחת אדמה', en: 'Villages buried under earth', detail_he: 'שיטת טיהור: הריסה וכיסוי בעפר נקי', detail_en: 'Decontamination method: demolish and cover with clean soil' },
  ],
};

// =================== RADIATION DATA ===================
export const ISOTOPES = [
  { name: 'Iodine-131', symbol: 'I-131', half: '8.0 days',
    he: 'יוד-131', target_he: 'בלוטת התריס', target_en: 'Thyroid gland',
    danger_he: 'נשאף או נבלע במזון/חלב מזוהם. גורם סרטן בלוטת התריס בילדים.',
    danger_en: 'Inhaled or ingested via contaminated food/milk. Causes childhood thyroid cancer.',
    released: '~1,760 PBq', color: '#a855f7' },
  { name: 'Cesium-137', symbol: 'Cs-137', half: '30.17 years',
    he: 'צסיום-137', target_he: 'רקמות רכות', target_en: 'Soft tissues',
    danger_he: 'זיהום ארוך-טווח של אדמה ומזון. עד היום באזור ההדרה.',
    danger_en: 'Long-term soil and food contamination. Still present in exclusion zone today.',
    released: '~85 PBq', color: '#dc2626' },
  { name: 'Strontium-90', symbol: 'Sr-90', half: '28.8 years',
    he: 'סטרונציום-90', target_he: 'עצמות', target_en: 'Bones',
    danger_he: 'מחקה סידן ומשתלב בעצמות. גורם סרטן עצם וללוקמיה.',
    danger_en: 'Mimics calcium, embeds in bones. Causes bone cancer and leukemia.',
    released: '~10 PBq', color: '#f59e0b' },
  { name: 'Plutonium-239', symbol: 'Pu-239', half: '24,110 years',
    he: 'פלוטוניום-239', target_he: 'ריאות, עצמות, כבד', target_en: 'Lungs, bones, liver',
    danger_he: 'רעיל מאוד אם נשאף. נשאר באזור ההדרה למאות אלפי שנים.',
    danger_en: 'Highly toxic if inhaled. Remains in exclusion zone for hundreds of thousands of years.',
    released: '~0.03 PBq', color: '#22c55e' },
  { name: 'Xenon-133', symbol: 'Xe-133', half: '5.2 days',
    he: 'קסנון-133', target_he: 'גז אצילי', target_en: 'Noble gas',
    danger_he: 'התפזר באטמוספירה. דעך תוך שבועות. נמדד לראשונה בשבדיה.',
    danger_en: 'Dispersed in atmosphere. Decayed within weeks. First detected in Sweden.',
    released: '~6,500 PBq', color: '#06b6d4' },
];

export const DOSE_SCALE = [
  { mSv: 0.01, label_he: 'צילום שיניים', label_en: 'Dental X-ray', risk: 'safe' },
  { mSv: 0.1, label_he: 'צילום חזה', label_en: 'Chest X-ray', risk: 'safe' },
  { mSv: 2.4, label_he: 'קרינת רקע שנתית', label_en: 'Annual background radiation', risk: 'safe' },
  { mSv: 10, label_he: 'CT בטן', label_en: 'Abdominal CT scan', risk: 'low' },
  { mSv: 50, label_he: 'גבול עליון מקצועי שנתי', label_en: 'Annual occupational limit', risk: 'low' },
  { mSv: 100, label_he: 'סף עלייה ניכרת בסיכון לסרטן', label_en: 'Threshold for cancer risk increase', risk: 'medium' },
  { mSv: 250, label_he: 'מנה לליקווידטור ממוצע', label_en: 'Average liquidator dose', risk: 'medium' },
  { mSv: 1000, label_he: 'סף ARS קל (בחילות)', label_en: 'Mild ARS threshold (nausea)', risk: 'high' },
  { mSv: 4000, label_he: 'LD50 — מוות ב-50% תוך 30 ימים', label_en: 'LD50 — 50% death within 30 days', risk: 'extreme' },
  { mSv: 8000, label_he: 'LD100 — מוות ודאי תוך 3 שבועות', label_en: 'LD100 — certain death within 3 weeks', risk: 'extreme' },
  { mSv: 16000, label_he: 'הכבאים הראשונים בצ׳רנוביל', en_label: 'Chernobyl first firefighters', label_en: 'Chernobyl first firefighters', risk: 'extreme' },
  { mSv: 300000, label_he: 'מעל הליבה החשופה', label_en: 'Above exposed core', risk: 'extreme' },
];

// =================== GLOSSARY ===================
export const TERMS = [
  { cat: 'phys', he: 'ביקוע גרעיני', en: 'Nuclear Fission',
    def_he: 'תהליך שבו גרעין כבד (כמו אורניום-235) מתפצל לשני גרעינים קלים יותר תוך שחרור אנרגיה רבה ופליטת ניוטרונים.',
    def_en: 'Process in which a heavy nucleus (like U-235) splits into two lighter nuclei, releasing large amounts of energy and emitting neutrons.' },
  { cat: 'phys', he: 'תגובת שרשרת', en: 'Chain Reaction',
    def_he: 'תהליך שבו ניוטרונים מביקוע אחד גורמים לביקועים נוספים. בכור מבוקר, מספר הניוטרונים נשמר קבוע.',
    def_en: 'Process where neutrons from one fission cause additional fissions. In a controlled reactor, neutron count remains constant.' },
  { cat: 'phys', he: 'מקדם החללות (Void Coefficient)', en: 'Void Coefficient',
    def_he: 'מידת השינוי בתגובתיות הכור כתוצאה מיצירת בועות קיטור. ב-RBMK חיובי וגבוה (+4.7β) — פגם תכן קריטי.',
    def_en: 'Reactor reactivity change due to steam void formation. In RBMK positive and high (+4.7β) — critical design flaw.' },
  { cat: 'phys', he: 'קריטיות פרומפטית', en: 'Prompt Criticality',
    def_he: 'מצב שבו הכור הופך קריטי באמצעות ניוטרונים מהירים בלבד. ההספק יכול לזנק תוך מילישניות. זה מה שקרה ב-01:23:45.',
    def_en: 'State where reactor becomes critical via prompt neutrons alone. Power can spike within milliseconds.' },
  { cat: 'phys', he: 'מאט (Moderator)', en: 'Moderator',
    def_he: 'חומר שמאט ניוטרונים מהירים לטרמיים, כדי שיוכלו לגרום לביקוע. ב-RBMK: גרפיט. בכורים מערביים: מים.',
    def_en: 'Material slowing fast neutrons to thermal speeds. In RBMK: graphite. In Western reactors: pressurized water.' },
  { cat: 'phys', he: 'אורניום מועשר', en: 'Enriched Uranium',
    def_he: 'אורניום שבו הוגדל ריכוז האיזוטופ U-235 (הקל לביקוע) מעל הריכוז הטבעי (0.7%). דלק RBMK: 2.0% U-235.',
    def_en: 'Uranium with elevated U-235 isotope above natural (0.7%). RBMK fuel: 2.0% U-235.' },
  { cat: 'phys', he: 'הרעלת קסנון', en: 'Xenon Poisoning',
    def_he: 'הצטברות Xe-135 (תוצר ביקוע, מחצית-חיים 9.2 שעות) הסופח ניוטרונים בכמות גדולה ובכך מדכא את הכור. בכור פעיל הוא נבלע ע״י ניוטרון והופך ל-Xe-136 לא-רעיל. ב-26/4/86 גרם לקריסת הספק ל-30 MWt.',
    def_en: 'Xe-135 buildup (fission product, half-life 9.2 hours) absorbing massive neutron flux, suppressing reactor. In active reactor it absorbs neutron becoming non-toxic Xe-136. On 26/4/86 caused power crash to 30 MWt.' },
  { cat: 'phys', he: 'תגובתיות (Reactivity)', en: 'Reactivity',
    def_he: 'מידת הסטייה של הכור ממצב קריטי. תגובתיות חיובית = ההספק עולה. נמדד ביחידות δk/k או ב-β.',
    def_en: 'Reactor deviation from critical state. Positive reactivity = power rising. Measured in δk/k or β.' },
  { cat: 'phys', he: 'איזוטופים בקיעים (Fissile)', en: 'Fissile Isotopes',
    def_he: 'גרעינים שבהם פגיעת ניוטרון (אפילו איטי) גורמת לבקיעה. דוגמאות: U-235, Pu-239. בטבע יש רק U-235 — 0.72% מהאורניום הטבעי.',
    def_en: 'Nuclei in which neutron impact (even slow) causes fission. Examples: U-235, Pu-239. In nature only U-235 exists — 0.72% of natural uranium.' },
  { cat: 'phys', he: 'יוד-135', en: 'Iodine-135',
    def_he: 'איזוטופ רדיואקטיבי, אחד מתוצרי הביקוע הנפוצים של U-235. מתפרק בבטא לקסנון-135 (זמן מחצית-חיים 6.6 שעות).',
    def_en: 'Radioactive isotope, common fission product of U-235. Beta-decays to Xenon-135 (half-life 6.6 hours).' },
  { cat: 'phys', he: 'קסנון-136', en: 'Xenon-136',
    def_he: 'איזוטופ יציב ולא-רעיל. נוצר כש-Xe-135 בולע ניוטרון בכור פעיל. כך הכור "אוכל" את ההרעלה שלו במצב פעולה רגיל.',
    def_en: 'Stable, non-toxic isotope. Formed when Xe-135 absorbs a neutron in active reactor. Thus reactor "consumes" its own poisoning during normal operation.' },

  { cat: 'reactor', he: 'RBMK', en: 'RBMK (Reaktor Bolshoy Moshchnosti Kanalnyy)',
    def_he: 'כור גרפיט-מים סובייטי במבנה תעלות. חסר מבנה הכלה מערבי. כל הכורים מסוג זה שודרגו אחרי האסון.',
    def_en: 'Soviet graphite-moderated, water-cooled, channel-type reactor. Lacks Western containment. All upgraded post-disaster.' },
  { cat: 'reactor', he: 'מוטות בקרה', en: 'Control Rods',
    def_he: 'מוטות מחומרים סופחי-ניוטרונים (בורון, קדמיום). מחדירים אותם לליבה כדי להאט/לעצור. ב-RBMK: 211 מוטות B₄C עם פגם הקצה הגרפיטי.',
    def_en: 'Rods of neutron-absorbing materials (boron, cadmium). Inserted to slow/stop reaction. In RBMK: 211 B₄C rods with graphite tip flaw.' },
  { cat: 'reactor', he: 'AZ-5', en: 'AZ-5 (Emergency Scram)',
    def_he: 'כפתור עצירת חירום. מחדיר את כל המוטות תוך 18-21 שניות. ב-26/4/86 בשעה 01:23:40 הופעל וגרם לפיצוץ במקום לעצור.',
    def_en: 'Emergency scram button. Inserts all rods within 18-21 seconds. On 26/4/86 at 01:23:40 activated and caused explosion.' },
  { cat: 'reactor', he: 'ECCS', en: 'ECCS — Emergency Core Cooling',
    def_he: 'מערכת גיבוי שמציפה את הכור במים אם הקירור הראשי נכשל. בצ׳רנוביל נותקה ידנית — הפרת רישיון.',
    def_en: 'Backup system flooding reactor with water if primary cooling fails. At Chernobyl manually disabled — license violation.' },
  { cat: 'reactor', he: 'ORM', en: 'ORM — Operational Reactivity Margin',
    def_he: 'מספר המוטות שיש להחדיר לליבה כדי להגיע לסף תגובתיות. מינימום מותר: 30. בעת האסון: 8.',
    def_en: 'Number of rods needed to reach reactivity threshold. Allowed minimum: 30. At disaster time: 8.' },
  { cat: 'reactor', he: 'תופי הפרדה', en: 'Steam Separator Drums',
    def_he: '4 גלילים אופקיים (30 מ׳) המפרידים את תערובת המים-קיטור היוצאת מהליבה.',
    def_en: '4 horizontal cylinders (30m) separating water-steam mixture from core.' },
  { cat: 'reactor', he: 'מכל לחץ', en: 'Pressure Vessel',
    def_he: 'מכל פלדה-בטון העוטף את הכור. ב-RBMK: 26 מ׳ × 21.6 מ׳, ללא containment חיצוני.',
    def_en: 'Steel-concrete vessel housing reactor. In RBMK: 26m × 21.6m, no outer containment.' },
  { cat: 'reactor', he: 'תעלת לחץ', en: 'Pressure Tube',
    def_he: 'צינור זירקאלוי שמכיל תעלת דלק עם מים זורמים. RBMK יש 1,661 מהם.',
    def_en: 'Zircaloy tube containing fuel channel with flowing water. RBMK has 1,661.' },
  { cat: 'reactor', he: '"סכמה E" (מגן ביולוגי)', en: '"Schema E" Bio-Shield',
    def_he: 'לוח פלדה-בטון 2,000 ט׳ העוטף את החלק העליון של הכור. בפיצוץ נזרק לאוויר ונחת בזווית.',
    def_en: 'Steel-concrete plate, 2,000 t, capping reactor top. Second explosion hurled it; landed at angle.' },
  { cat: 'reactor', he: 'משאבת זרימה ראשית (MCP)', en: 'Main Circulation Pump',
    def_he: 'משאבה צנטריפוגלית שדוחפת מי קירור דרך הכור. RBMK יש 8 (6 פעילות + 2 רזרבה).',
    def_en: 'Centrifugal pump pushing coolant through reactor. RBMK has 8 (6 active + 2 reserve).' },
  { cat: 'reactor', he: 'גנרטורי דיזל חירום', en: 'Emergency Diesel Generators',
    def_he: '3 גנרטורים שמספקים חשמל למשאבות הקירור בעת תקלה. זמן ההתנעה ~דקה — הסיבה לניסוי הטורבינה.',
    def_en: '3 generators supplying power to cooling pumps during failure. Startup ~1 minute — the reason for the turbine test.' },
  { cat: 'reactor', he: 'PWR (Pressurized Water Reactor)', en: 'PWR',
    def_he: 'כור מים בלחץ — הסוג הנפוץ ביותר במערב. מים משמשים גם כמאט וגם כקירור. כשמים מתאדים, התגובה יורדת — בטיחות מובנית.',
    def_en: 'Pressurized Water Reactor — most common Western type. Water serves as both moderator and coolant. When water vaporizes, reaction drops — built-in safety.' },
  { cat: 'reactor', he: 'BWR (Boiling Water Reactor)', en: 'BWR',
    def_he: 'כור מים רותחים — סוג מערבי. דומה ל-PWR אך הקיטור נוצר ישירות בליבה. בטיחות מובנית ממים-מאט.',
    def_en: 'Boiling Water Reactor — Western type. Similar to PWR but steam created directly in core. Built-in safety from water-moderator.' },

  { cat: 'rad', he: 'תסמונת קרינה חריפה (ARS)', en: 'Acute Radiation Syndrome',
    def_he: 'מחלה הנגרמת מחשיפה למנת קרינה גבוהה (>1 Gy) בזמן קצר. תסמינים: בחילות, פגיעה במח עצם, פגיעה במערכת העיכול, מוות.',
    def_en: 'Disease from high radiation exposure (>1 Gy) in short time. Symptoms: nausea, bone marrow damage, GI damage, death.' },
  { cat: 'rad', he: 'מנת קרינה (Dose)', en: 'Radiation Dose',
    def_he: 'כמות הקרינה שנספגה ברקמת הגוף. נמדדת ב-Gray (Gy) לאנרגיה נספגת או Sievert (Sv) לנזק ביולוגי משוקלל.',
    def_en: 'Radiation absorbed by tissue. Measured in Gray (Gy) for absorbed energy or Sievert (Sv) for biological-weighted damage.' },
  { cat: 'rad', he: 'קרן גמא', en: 'Gamma Rays',
    def_he: 'קרינה אלקטרומגנטית בעלת אנרגיה גבוהה ויכולת חדירה גדולה. כדי לעצור: עופרת או בטון בעובי משמעותי.',
    def_en: 'High-energy electromagnetic radiation with great penetration. To stop: thick lead or concrete.' },
  { cat: 'rad', he: 'קרן ביתא', en: 'Beta Particles',
    def_he: 'אלקטרונים מהירים. עוצרים על ידי לוח אלומיניום או בגדים עבים. סכנה במגע עורי או בליעה.',
    def_en: 'Fast electrons. Stopped by aluminum sheet or thick clothing. Danger via skin contact or ingestion.' },
  { cat: 'rad', he: 'יוד-131', en: 'Iodine-131',
    def_he: 'איזוטופ רדיואקטיבי בעל מחצית-חיים של 8 ימים. נבלע ע״י בלוטת התריס וגורם סרטן בלוטת התריס בילדים.',
    def_en: 'Radioactive isotope with 8-day half-life. Absorbed by thyroid gland, causing childhood thyroid cancer.' },
  { cat: 'rad', he: 'צסיום-137', en: 'Cesium-137',
    def_he: 'איזוטופ רדיואקטיבי בעל מחצית-חיים של 30 שנה. אחראי לזיהום ארוך-טווח של אדמה ומזון.',
    def_en: 'Radioactive isotope with 30-year half-life. Responsible for long-term soil and food contamination.' },
  { cat: 'rad', he: 'סטרונציום-90', en: 'Strontium-90',
    def_he: 'מחקה סידן ומשתלב בעצמות. מחצית-חיים: 29 שנה. גורם סרטן עצם ולוקמיה.',
    def_en: 'Mimics calcium, embeds in bones. Half-life: 29 years. Causes bone cancer and leukemia.' },
  { cat: 'rad', he: 'פלוטוניום-239', en: 'Plutonium-239',
    def_he: 'איזוטופ של פלוטוניום. מחצית-חיים: 24,000 שנה. רעיל מאוד אם נשאף או נבלע.',
    def_en: 'Plutonium isotope. Half-life: 24,000 years. Highly toxic if inhaled or ingested.' },
  { cat: 'rad', he: 'מחצית-חיים', en: 'Half-Life',
    def_he: 'הזמן הנדרש לחצי מאיזוטופ רדיואקטיבי להתפרק. דוגמאות: I-131 (8 ימים), Cs-137 (30 שנה).',
    def_en: 'Time for half a radioactive isotope to decay. Examples: I-131 (8 days), Cs-137 (30 years).' },
  { cat: 'rad', he: 'PBq (פטה-בקרל)', en: 'PBq (Petabecquerel)',
    def_he: 'יחידת מדידת פעילות רדיואקטיבית. 1 PBq = 10¹⁵ פירוקים בשנייה. מצ׳רנוביל שוחרר 5,300 PBq של Cs-137.',
    def_en: 'Unit of radioactive activity. 1 PBq = 10¹⁵ decays per second. Chernobyl released 5,300 PBq of Cs-137.' },
  { cat: 'rad', he: 'גריי (Gy)', en: 'Gray (Gy)',
    def_he: 'יחידה לאנרגיית קרינה נספגת. 1 Gy = 1 J/kg של רקמה. 4-5 Gy לכל הגוף = LD50.',
    def_en: 'Unit of absorbed radiation energy. 1 Gy = 1 J/kg of tissue. 4-5 Gy whole-body = LD50.' },
  { cat: 'rad', he: 'סיברט (Sv)', en: 'Sievert (Sv)',
    def_he: 'יחידה למנת קרינה משוקללת ביולוגית. גמא: 1 Sv = 1 Gy. אלפא: 1 Sv = 0.05 Gy.',
    def_en: 'Unit of biologically-weighted dose. Gamma: 1 Sv = 1 Gy. Alpha: 1 Sv = 0.05 Gy.' },

  { cat: 'dis', he: 'ליקווידטורים', en: 'Liquidators',
    def_he: 'כינוי לכ-600,000 חיילים, פועלים, ומומחים שעבדו על ניקוי האסון בין 1986-1990.',
    def_en: 'Term for ~600,000 soldiers, workers, and specialists who worked on disaster cleanup 1986-1990.' },
  { cat: 'dis', he: 'אזור ההדרה', en: 'Exclusion Zone',
    def_he: 'אזור 30 ק״מ מסביב לכור (מאוחר יותר 2,600 קמ״ר) שפינוי כפוי ואסור להיכנס אליו. עד היום פעיל.',
    def_en: '30 km zone around reactor (later 2,600 km²) with forced evacuation and entry prohibited.' },
  { cat: 'dis', he: 'סרקופג (Object Shelter)', en: 'Sarcophagus',
    def_he: 'מבנה הבטון שהוקם על הריסות יחידה 4 ב-1986 כדי לעצור פליטת קרינה. תכנון לעמידות 30 שנה.',
    def_en: 'Concrete structure built over Unit 4 ruins in 1986 to stop radiation emission. Designed for 30 years.' },
  { cat: 'dis', he: 'סגירה חדשה (NSC)', en: 'New Safe Confinement',
    def_he: 'קונסטרוקציה מתכת ענקית (108 מ׳, 36,000 ט׳), הגדולה בעולם, שהוסטה ב-29/11/2016 על הסרקופג הישן.',
    def_en: 'Massive metal structure (108m, 36,000 t), world\'s largest, slid over old sarcophagus on 29/11/2016.' },
  { cat: 'dis', he: 'פינוי פריפיאט', en: 'Pripyat Evacuation',
    def_he: 'פינוי 49,000 תושבים תוך 3 שעות ב-27/4/1986 ב-1,200 אוטובוסים. ההודעה: "חזרו תוך 3 ימים".',
    def_en: 'Evacuation of 49,000 residents within 3 hours on 27/4/1986 in 1,200 buses. Announcement: "Return in 3 days".' },
  { cat: 'dis', he: '"רגל הפיל"', en: '"Elephant\'s Foot"',
    def_he: 'מסת לבה רדיואקטיבית (חרבית — Corium) שזרמה ממה שנותר מהליבה למרתפים. ב-1986 קרינה של 8,000 R/h.',
    def_en: 'Mass of radioactive lava (corium) that flowed from core remnants to basements. In 1986 emitted 8,000 R/h.' },
  { cat: 'dis', he: 'חרבית (Corium)', en: 'Corium',
    def_he: 'תערובת מותכת של דלק גרעיני, פלדה, גרפיט, ובטון, שנוצרה בעת הריסת הליבה.',
    def_en: 'Molten mixture of nuclear fuel, steel, graphite, and concrete formed during core meltdown.' },

  { cat: 'fire', he: 'מנ״פ', en: 'SCBA — Self-Contained Breathing Apparatus',
    def_he: 'מערכת נשימה פתוחה — מכל אוויר נישא על הגב המספק אוויר נקי לכבאי. בצ׳רנוביל ב-1986 לא היה זמין לכל הצוותים.',
    def_en: 'Back-mounted air tank supplying clean air. At Chernobyl 1986 not available to all crews.' },
  { cat: 'fire', he: 'מב״ר', en: 'Initial Isolation Distance',
    def_he: 'מרחק בידוד ראשוני — מרחק מינימלי שצריך לפנות סביב חומר מסוכן. בקרינה גרעינית: 100 מ׳ במבנה סגור / 200 מ׳ באוויר פתוח (ERG 2024).',
    def_en: 'Minimum distance to evacuate around hazmat. For nuclear radiation: 100m enclosed / 200m open air (ERG 2024).' },
  { cat: 'fire', he: 'ERG', en: 'ERG — Emergency Response Guide',
    def_he: 'מדריך התגובה לחירום — מדריך בינלאומי לטיפול בחומרים מסוכנים. מהדורת 2024 כוללת כללי טיפול לחומרים רדיואקטיביים.',
    def_en: 'International hazmat response guide. 2024 edition includes radioactive material handling protocols.' },
  { cat: 'fire', he: 'ספיחה', en: 'Adsorption',
    def_he: 'הצמדה של מולקולות חומר לפני שטח של חומר אחר. לעומת בליעה (Absorption) שהיא חדירה. רלוונטי לטיהור קרינה.',
    def_en: 'Adhesion of substance molecules to another\'s surface. Vs absorption which is penetration.' },
  { cat: 'fire', he: 'טיהור', en: 'Decontamination',
    def_he: 'הסרת חומר רדיואקטיבי מציוד, מבנים, או אנשים. שיטות: שטיפה במים מיוחדים, חיתוך וקבירת אדמה (5 ס״מ עליונים), הריסת בתים.',
    def_en: 'Removal of radioactive material from equipment, buildings, or people.' },

  { cat: 'org', he: 'IAEA', en: 'IAEA — International Atomic Energy Agency',
    def_he: 'סוכנות האנרגיה האטומית הבינלאומית. פרסמה את דוח INSAG-7 (1992) — הניתוח הסמכותי של אסון צ׳רנוביל.',
    def_en: 'International Atomic Energy Agency. Published INSAG-7 (1992) — authoritative analysis of Chernobyl disaster.' },
  { cat: 'org', he: 'INSAG-7', en: 'INSAG-7',
    def_he: 'דוח קבוצת הייעוץ הבינלאומית לבטיחות גרעינית, 1992. הניתוח הרשמי של אסון צ׳רנוביל.',
    def_en: 'International Nuclear Safety Advisory Group report, 1992. Official analysis of Chernobyl disaster.' },
  { cat: 'org', he: 'UNSCEAR', en: 'UNSCEAR',
    def_he: 'הוועדה המדעית של האו״ם להשפעות הקרינה האטומית. דוח 2008 הוא הבסיס לסיכומי בריאות מאסון צ׳רנוביל.',
    def_en: 'UN Scientific Committee on the Effects of Atomic Radiation. 2008 report is foundation for Chernobyl health summaries.' },
  { cat: 'org', he: 'WHO', en: 'WHO — World Health Organization',
    def_he: 'דוח 2006 של WHO ("Health Effects of the Chernobyl Accident") הוא המקור המרכזי להשלכות הבריאותיות לטווח ארוך.',
    def_en: 'WHO 2006 report is primary source for long-term health consequences.' },
];

export const TERM_CAT: Record<string, { c: string; he: string; en: string }> = {
  phys: { c: '#a855f7', he: 'פיזיקה גרעינית', en: 'Nuclear Physics' },
  reactor: { c: '#c8a44e', he: 'מערכות הכור', en: 'Reactor Systems' },
  rad: { c: '#22c55e', he: 'קרינה ובריאות', en: 'Radiation & Health' },
  dis: { c: '#dc2626', he: 'האסון', en: 'The Disaster' },
  fire: { c: '#f59e0b', he: 'כבאות וחומ״ס', en: 'Firefighting & HazMat' },
  org: { c: '#06b6d4', he: 'ארגונים', en: 'Organizations' },
};

// =================== SOURCES ===================
export const SOURCES = [
  { cat: 'iaea', icon: '📋', title: 'IAEA INSAG-7 (1992)', subtitle: 'The Chernobyl Accident: Updating of INSAG-1',
    desc_he: 'הניתוח הסמכותי הרשמי של אסון צ׳רנוביל. מאשים גם פגמי תכן של RBMK וגם טעויות מפעילים. מסמך הבסיס לכל ניתוח מקצועי.',
    desc_en: 'Authoritative official analysis. Blames both RBMK design flaws and operator errors. Foundation document.',
    url: 'https://www-pub.iaea.org/MTCD/publications/PDF/Pub913e_web.pdf', year: 1992 },
  { cat: 'iaea', icon: '📋', title: 'IAEA INSAG-1 (1986)', subtitle: 'Original Post-Accident Report',
    desc_he: 'הדוח הראשון אחרי האסון. הוצא ב-1986 עוד תחת ההגדרה הסובייטית — שהאשים בעיקר את המפעילים. תוקן ב-INSAG-7.',
    desc_en: 'First post-accident report. Published 1986 under Soviet narrative — primarily blamed operators. Later corrected by INSAG-7.',
    url: 'https://www-pub.iaea.org/MTCD/publications/PDF/Pub913e_web.pdf', year: 1986 },
  { cat: 'unscear', icon: '🔬', title: 'UNSCEAR 2008 Report — Annex D', subtitle: 'Health effects from Chernobyl',
    desc_he: 'דוח הוועדה המדעית של האו״ם. הסיכום המקיף של ההשפעות הבריאותיות לטווח ארוך. 6,000+ מקרי סרטן בלוטת התריס בילדים.',
    desc_en: 'UN Scientific Committee report. Comprehensive summary of long-term health effects.',
    url: 'https://www.unscear.org/docs/reports/2008/11-80076_Report_2008_Annex_D.pdf', year: 2008 },
  { cat: 'who', icon: '🏥', title: 'WHO 2006 Report', subtitle: 'Health Effects of the Chernobyl Accident',
    desc_he: 'דוח ארגון הבריאות העולמי. שנה לאחר 20 לאסון. מקור עיקרי להשלכות בריאותיות לטווח ארוך.',
    desc_en: 'World Health Organization report. 20 years after disaster. Primary source for long-term health.',
    url: 'https://www.who.int/publications/i/item/9241594179', year: 2006 },
  { cat: 'nrc', icon: '⚛', title: 'US NRC NUREG-1250', subtitle: 'Report on the Accident at Chernobyl NPP',
    desc_he: 'דוח ועדת הרגולציה הגרעינית האמריקאית. ניתוח טכני מפורט מנקודת מבט מערבית.',
    desc_en: 'US Nuclear Regulatory Commission report. Detailed technical analysis from Western perspective.',
    url: 'https://www.nrc.gov/docs/ML0716/ML071690245.pdf', year: 1987 },
  { cat: 'book', icon: '📚', title: 'Adam Higginbotham — Midnight in Chernobyl', subtitle: 'The Untold Story',
    desc_he: 'הספר העיתונאי הטוב ביותר על האסון. מחקר של 5 שנים, ראיונות ניצולים, מסמכים סובייטיים. כיסוי דקה-אחר-דקה.',
    desc_en: 'Best journalistic book on disaster. 5 years research, survivor interviews, Soviet documents. Minute-by-minute.',
    url: 'https://www.simonandschuster.com/books/Midnight-in-Chernobyl/Adam-Higginbotham/9781501134630', year: 2019 },
  { cat: 'book', icon: '📚', title: 'Serhii Plokhy — Chernobyl', subtitle: 'History of a Tragedy (Pulitzer 2018)',
    desc_he: 'ספר מהיסטוריון אוקראיני בהרווארד. זוכה פרס פוליצר 2018. ניתוח רחב יותר של ההקשר הסובייטי.',
    desc_en: 'Book by Ukrainian historian at Harvard. Pulitzer Prize 2018. Broader Soviet context analysis.',
    url: 'https://www.basicbooks.com/titles/serhii-plokhy/chernobyl/9781541617094/', year: 2018 },
  { cat: 'book', icon: '📚', title: 'Svetlana Alexievich — Voices from Chernobyl', subtitle: 'Nobel Prize 2015',
    desc_he: 'ספר עדויות אישיות של ניצולים, ליקווידטורים, ובני משפחותיהם. הזוכה בנובל לספרות 2015 בהשראה ממנו.',
    desc_en: 'Personal testimonies from survivors, liquidators, and family members. Author won Nobel 2015.',
    url: 'https://www.penguinrandomhouse.com/books/93009/voices-from-chernobyl-by-svetlana-alexievich/', year: 1997 },
  { cat: 'doc', icon: '🎬', title: 'HBO — Chernobyl (2019 miniseries)', subtitle: '5-episode dramatization',
    desc_he: 'סדרת המיני המוערכת מאוד. ברובה מדויקת מבחינה היסטורית. הפיקה מודעות ציבורית עצומה.',
    desc_en: 'Highly acclaimed miniseries. Mostly historically accurate. Generated huge public awareness.',
    url: 'https://www.hbo.com/chernobyl', year: 2019 },
  { cat: 'doc', icon: '🎬', title: 'BBC — Chernobyl: The Real Story', subtitle: 'Documentary',
    desc_he: 'דוקומנטרי BBC עם ראיונות עד והצגת מסמכים. השלמה טובה לסדרת HBO.',
    desc_en: 'BBC documentary with eyewitness interviews and document presentation.',
    url: 'https://www.bbc.co.uk/programmes/p07cyh3y', year: 2019 },
  { cat: 'web', icon: '🌐', title: 'Chernobyl Gallery', subtitle: 'Photo archive',
    desc_he: 'ארכיון תמונות מקיף של האסון, פריפיאט, אזור ההדרה.',
    desc_en: 'Comprehensive photo archive of disaster, Pripyat, exclusion zone.',
    url: 'https://chernobylgallery.com/', year: null },
  { cat: 'web', icon: '🌐', title: 'World Nuclear Association', subtitle: 'Chernobyl Accident Technical Summary',
    desc_he: 'סיכום טכני מקיף של האסון על ידי האגודה הגרעינית העולמית.',
    desc_en: 'Comprehensive technical summary by World Nuclear Association.',
    url: 'https://world-nuclear.org/information-library/safety-and-security/safety-of-plants/chernobyl-accident.aspx', year: null },
  { cat: 'web', icon: '🌐', title: 'Official Exclusion Zone Site', subtitle: 'Government info',
    desc_he: 'אתר רשמי של אזור ההדרה האוקראיני. מידע נוכחי על מצב הסגירה החדשה (NSC), פעילות מחקר, וטיולים.',
    desc_en: 'Official Ukrainian Exclusion Zone site. Current info on NSC, research, and tours.',
    url: 'https://www.chernobyl-tour.com/', year: null },
  { cat: 'sci', icon: '🇮🇱', title: 'מכון דוידסון — אורי טייכמן', subtitle: 'התאונה הגרעינית הקשה ביותר',
    desc_he: 'הסבר מקצועי בעברית של הזרוע החינוכית של מכון ויצמן. כולל: 3 ניסויי טורבינה קודמים שנכשלו, 3 גנרטורי דיזל, מנגנון בטיחות מובנה של כורי מים-מאט.',
    desc_en: 'Professional Hebrew explanation by Weizmann Institute educational arm. Includes: 3 previous failed turbine tests, 3 diesel generators, water-moderator built-in safety mechanism.',
    url: 'https://davidson.org.il/read-experience/sciencepanorama/%D7%94%D7%AA%D7%90%D7%95%D7%A0%D7%94-%D7%94%D7%92%D7%A8%D7%A2%D7%99%D7%A0%D7%99%D7%AA-%D7%94%D7%A7%D7%A9%D7%94-%D7%91%D7%99%D7%95%D7%AA%D7%A8/', year: 2019 },
  { cat: 'sci', icon: '🔬', title: 'Chernobyl Forum (IAEA/WHO/UNDP) — 2005', subtitle: 'Chernobyl\'s Legacy',
    desc_he: 'דוח משותף של 8 סוכנויות או״ם. הסיכום הסמכותי של ההשפעות הבריאותיות והסביבתיות לאחר 20 שנה.',
    desc_en: 'Joint report by 8 UN agencies. Authoritative summary of health and environmental effects 20 years after.',
    url: 'https://www.iaea.org/sites/default/files/chernobyl.pdf', year: 2005 },
  { cat: 'sci', icon: '🔬', title: 'Cardis et al. — Cancer consequences (2006)', subtitle: 'IJC',
    desc_he: 'מאמר אקדמי המעריך 16,000 מקרי סרטן עודפים באירופה כתוצאה מצ׳רנוביל בעשורים הקרובים.',
    desc_en: 'Academic paper estimating 16,000 excess cancer cases in Europe over coming decades.',
    url: 'https://onlinelibrary.wiley.com/doi/10.1002/ijc.22037', year: 2006 },
];

export const SRC_CAT: Record<string, { c: string; he: string; en: string }> = {
  iaea: { c: '#c8a44e', he: 'IAEA', en: 'IAEA' },
  unscear: { c: '#22c55e', he: 'UNSCEAR', en: 'UNSCEAR' },
  who: { c: '#06b6d4', he: 'WHO', en: 'WHO' },
  nrc: { c: '#a855f7', he: 'NRC', en: 'NRC US' },
  book: { c: '#f59e0b', he: 'ספרים', en: 'Books' },
  doc: { c: '#ef4444', he: 'דוקומנטרי', en: 'Documentaries' },
  web: { c: '#94a3b8', he: 'אתרים', en: 'Websites' },
  sci: { c: '#06b6d4', he: 'מחקר אקדמי', en: 'Academic' },
};

// =================== TOC SECTIONS ===================
export const SECTIONS = [
  { id: 'hero', he: 'פתיחה', en: 'Intro', emoji: '🏠' },
  { id: 'timeline', he: 'ציר זמן', en: 'Timeline', emoji: '📅' },
  { id: 'reactor-general', he: 'כור גרעיני', en: 'Nuclear Reactor', emoji: '⚛' },
  { id: 'rbmk', he: 'RBMK והכשלים', en: 'RBMK & Failures', emoji: '☢' },
  { id: 'response', he: 'הכלה וכיבוי', en: 'Containment', emoji: '🚒' },
  { id: 'casualties', he: 'נפגעים', en: 'Casualties', emoji: '🕯' },
  { id: 'radiation', he: 'קרינה', en: 'Radiation', emoji: '📡' },
  { id: 'glossary', he: 'מונחים', en: 'Glossary', emoji: '📖' },
  { id: 'sources', he: 'קישורים', en: 'Sources', emoji: '📚' },
  { id: 'presentation', he: 'מצגת', en: 'Presentation', emoji: '🎯' },
  { id: 'infographic', he: 'אינפוגרפיקה', en: 'Infographic', emoji: '🎨' },
];
